module Italy where
 
import ParcoursDB.Country
import ParcoursDB.Location

italianLocation :: String -> Location
italianLocation loc = Location loc Italy

-- A
abbiategrasso   = italianLocation "Abbiategrasso"
agrigento       = italianLocation "Agrigento"
alghero         = italianLocation "Alghero"
amatrice        = italianLocation "Amatrice"
andalo          = italianLocation "Andalo"
aosta           = italianLocation "Aosta"
arezzo          = italianLocation "Arezzo"
arzignano       = italianLocation "Arzignano"
asiago          = italianLocation "Asiago"
asolo           = italianLocation "Asolo"
assisi          = italianLocation "Assisi"
auronzoDiCadore = italianLocation "Auronzo di Cadore"

-- B
bagnoDiRomagna = italianLocation "Bagno di Romagna"
bardonecchia   = italianLocation "Bardonecchia (Monte Jafferau)"
bari           = italianLocation "Bari"
barletta       = italianLocation "Barletta"
bellaria       = italianLocation "Bellaria"
bergamo        = italianLocation "Bergamo"
bibione        = italianLocation "Bibione"
blockhaus      = italianLocation "Blockhaus"
bologna        = italianLocation "Bologna"
borgo          = italianLocation "Borgo Val di Taro"
bormio         = italianLocation "Bormio"
borno          = italianLocation "Borno"
bressanone     = italianLocation "Bressanone"
bucchianico    = italianLocation "Bucchianico"

-- C
cagliari                  = italianLocation "Cagliari"
caltagirone               = italianLocation "Caltagirone"
caltanissetta             = italianLocation "Caltanissetta"
camaiore                  = italianLocation "Camaiore"
campiBisenzio             = italianLocation "Campi Bisenzio"
campiSalentina            = italianLocation "Campi Salentina"
campotenese               = italianLocation "Campotenese"
canazei                   = italianLocation "Canazei"
cascia                    = italianLocation "Cascia"
cascina                   = italianLocation "Cascina"
cassanoDAdda              = italianLocation "Cassano d'Adda"
castellania               = italianLocation "Castellania"
castelnuouvoDiValDiCecina = italianLocation "Castelnuouvo di Val di Cecina"
castelraimondo            = italianLocation "Castelraimondo"
castelrotto               = italianLocation "Castelrotto"            
castigilioneDellaPescaia  = italianLocation "Castiglione della Pescaia"
castrovillari             = italianLocation "Castrovillari"
catania                   = italianLocation "Catania"
catanzaro                 = italianLocation "Catanzaro"
cefalu                    = italianLocation "Cefalu"
cepagatti                 = italianLocation "Cepagatti"
cervinia                  = italianLocation "Cervinia"
chieti                    = italianLocation "Chieti"
cittareale                = italianLocation "Cittareale"
cles                      = italianLocation "Cles"
como                      = italianLocation "Como"
corvara                   = italianLocation "Corvara"
cosenza                   = italianLocation "Cosenza"
cuneo                     = italianLocation "Cuneo"

-- D
dimaro     = italianLocation "Dimaro"
donoratico = italianLocation "Donoratico"

-- E
empoli      = italianLocation "Empoli"
esanatoglia = italianLocation "Esanatoglia"
etna        = italianLocation "Etna"

-- F
ferrara = italianLocation "Ferrara"
fiuggi  = italianLocation "Fiuggi"
foggia  = italianLocation "Foggia"
foligno = italianLocation "Foligno"
forli   = italianLocation "Forlì"

-- G
gatteoAMare  = italianLocation "Gatteo a Mare"
genoa        = italianLocation "Genoa"
giulianova   = italianLocation "Giulianova"
gualdoTadino = italianLocation "Gualdo Tadino"
guardiagrele = italianLocation "Guardiagrele"
guillestre   = italianLocation "Guillestre"

-- I
imola      = italianLocation "Imola"
imperia    = italianLocation "Imperia"
indicatore = italianLocation "Indicatore"
iseo       = italianLocation "Iseo"

-- L
lanciano          = italianLocation "Lanciano"
lerici            = italianLocation "Lerici"
lidoDiCamaiore    = italianLocation "Lido di Camaiore"
lidoDiJesolo      = italianLocation "Lido di Jesolo"
lignanoSabbiadoro = italianLocation "Lignano Sabbiadoro"
livorno           = italianLocation "Livorno"
longarone         = italianLocation "Longarone"

-- M
madesimo                  = italianLocation "Madesimo"
mantua                    = italianLocation "Mantua"
marinaDiPisa              = italianLocation "Marina di Pisa"
marinaDiSanVito           = italianLocation "Marina di San Vito"
messina                   = italianLocation "Messina"
milan                     = italianLocation "Milan"
modena                    = italianLocation "Modena"
molfetta                  = italianLocation "Molfetta"
molveno                   = italianLocation "Molveno"
montalcino                = italianLocation "Montalcino"
montaltoDiCastro          = italianLocation "Montalto di Castro"
monteSanVicino            = italianLocation "Monte San Vicino"
monteTerminillo           = italianLocation "Monte Terminillo"
montecatiniTerme          = italianLocation "Montecatini Terme"
montefalco                = italianLocation "Montefalco"
monteneroDiBisaccia       = italianLocation "Montenero di Bisaccia"
montevergineDiMercogliano = italianLocation "Montevergine Di Mercogliano"
monteZoncolan             = italianLocation "Monte Zoncolan"
monza                     = italianLocation "Monza"
mountEtna                 = italianLocation "Mount Etna"
muggio                    = italianLocation "Muggio"

-- N
narniScalo            = italianLocation "Narni Scalo"
nervesaDellaBattaglia = italianLocation "Nervesa della Battaglia"
noale                 = italianLocation "Noale"

-- O
olbia   = italianLocation "Olbia"
ortona  = italianLocation "Ortona"
orvieto = italianLocation "Orvieto"
osimo   = italianLocation "Osimo"

-- P
palinuro         = italianLocation "Palinuro"
parma            = italianLocation "Parma"
pavia            = italianLocation "Pavia"
pedara           = italianLocation "Pedara"
penne            = italianLocation "Penne"
peschici         = italianLocation "Peschici"
pescoSannita     = italianLocation "Pesco Sannita"
pila             = italianLocation "Pila"
pinerolo         = italianLocation "Pinerolo"
pisa             = italianLocation "Pisa"
pizzo            = italianLocation "Pizzo"
poggio           = italianLocation "Poggio di San Remo"
pomarance        = italianLocation "Pomarance"
ponte            = italianLocation "Ponte"
pontedera        = italianLocation "Pontedera"
pordenone        = italianLocation "Pordenone"
portoSantElpidio = italianLocation "Porto Sant'Elpidio"
portoferraio     = italianLocation "Portoferraio"
potenza          = italianLocation "Potenza"
prairaAMare      = italianLocation "Praira a Mare"
pratiDiTivo      = italianLocation "Prati di Tivo"
pratoNevoso      = italianLocation "Prato Nevoso"

-- R
recanati       = italianLocation "Recanati"
reggioCalabria = italianLocation "Reggio Calabria"
reggioEmilia   = italianLocation "Reggio Emilia"
rieti          = italianLocation "Rieti"
rimini         = italianLocation "Rimini"
rioMarina      = italianLocation "Rio Marina"
rivaDelGarda   = italianLocation "Riva del Garda"
risoul         = italianLocation "Risoul"
roccaraso      = italianLocation "Roccaraso"
rodiGarganico  = italianLocation "Rodi Garganico"
rome           = italianLocation "Rome"
rovereto       = italianLocation "Rovereto"
rovetta        = italianLocation "Rovetta"

-- S
saintVincent          = italianLocation "Saint-Vincent"
salaConsilina         = italianLocation "Sala Consilina"
salsomaggioreTerme    = italianLocation "Salsomaggiore Terme"
sanBenedettoDelTronto = italianLocation "San Benedetto del Tronto"
sanGiorgio            = italianLocation "San Giorgio del Sannio"
sanRemo               = italianLocation "San Remo"
sanRomolo             = italianLocation "San Romolo"
sanVigilloDiMarebbe   = italianLocation "San Vigillo di Marebbe"
sanVincenzo           = italianLocation "San Vincenzo"
sanVitoAlTagliamento  = italianLocation "San Vito al Tagliamento"
santAnnaDiVinadio     = italianLocation "Sant'Anna di Vinadio"
sappada               = italianLocation "Sappada"
saronno               = italianLocation "Saronno"
sestriere             = italianLocation "Sestriere"
sestola               = italianLocation "Sestola"
sirmione              = italianLocation "Sirmione"
soave                 = italianLocation "Soave"
sondrio               = italianLocation "Sondrio"
sorrento              = italianLocation "Sorrento"
sulmona               = italianLocation "Sulmona"
susa                  = italianLocation "Susa"

-- T
termamo           = italianLocation "Termamo"
termeLuigiane     = italianLocation "Terme Luigiane"
termoli           = italianLocation "Termoli"
terni             = italianLocation "Terni"
tirano            = italianLocation "Tirano"
tolmezzo          = italianLocation "Tolmezzo"
torino            = italianLocation "Torino"
tortona           = italianLocation "Tortona"
tortoli           = italianLocation "Tortolì"
treCimeDiLavaredo = italianLocation "Tre Cime di Lavaredo"
trento            = italianLocation "Trento"
trescore          = italianLocation "Trescore Balneario"
trieste           = italianLocation "Trieste"
turbigo           = italianLocation "Turbigo"
turin             = italianLocation "Turin"

-- V
valdengo       = italianLocation "Valdengo"
venariaReale   = italianLocation "Venaria Reale"
verona         = italianLocation "Verona"
villapianaLido = italianLocation "Villapiana Lido"

-- Z
zoldoAlto = italianLocation "Zoldo Alto"
