package parcoursdb

sealed trait Country
case object Andorra extends Country
case object Argentina extends Country
case object Austria extends Country
case object Australia extends Country
case object Belgium extends Country
case object Canada extends Country
case object Colombia extends Country
case object Croatia extends Country
case object Denmark extends Country
case object Estonia extends Country
case object Ethiopia extends Country
case object France extends Country
case object Germany extends Country
case object WestGermany extends Country
case object Greece extends Country
case object Ireland extends Country
case object Israel extends Country
case object Italy extends Country
case object Latvia extends Country
case object Luxembourg extends Country
case object Norway extends Country
case object Monaco extends Country
case object Netherlands extends Country
case object Poland extends Country
case object Portugal extends Country
case object PuertoRico extends Country
case object RepublicOfSouthAfrica extends Country
case object Russia extends Country
case object Spain extends Country
case object SanMarino extends Country
case object Slovenia extends Country
case object Slovakia extends Country
case object Sweden extends Country
case object Switzerland extends Country
case object UnitedKingdom extends Country
case object UnitedStates extends Country

object BelgianLocations {

    implicit val country:Country = Belgium

    def ans:Location     = { Location("Ans") }
    def antwerp:Location = { Location("Antwerp") }
    def arlon:Location   = { Location("Arlon") }

    def bastogne:Location   = { Location("Bastogne") }
    def beauraing:Location  = { Location("Beauraing") }
    def beringen:Location   = { Location("Beringen") }
    def beveren:Location    = { Location("Beveren") }
    def bornem:Location     = { Location("Bornem") }
    def brasschaat:Location = { Location("Brasschaat") }
    def bruges:Location     = { Location("Bruges") }
    def brussels:Location   = { Location("Brussels") }

    def charleroi:Location     = { Location("Charleroi") }
    def circuitZolder:Location = { Location("Circuit Zolder") }

    def deinze:Location  = { Location("Deinze") }
    def dinant:Location  = { Location("Dinant") }
    def esneux:Location  = { Location("Esneux") }
    def evergem:Location = { Location("Evergem") }

    def forest:Location = { Location( "Forest" ) }

    def gentbrugge:Location = { Location("Gentbrugge") }
    def ghent:Location      = { Location("Ghent") }

    def harelbeke:Location = { Location("Harelbeke") }
    def hasselt:Location   = { Location("Hasselt") }
    def herentals:Location = { Location("Herentals") }
    def hotton:Location    = { Location("Hotton") }
    def huy:Location       = { Location("Huy") }

    def jambes:Location = { Location("Jambes") }

    def leuven:Location  = { Location("Leuven") }
    def liege:Location   = { Location("Liège") }
    def lokeren:Location = { Location("Lokeren") }

    def marcheEnFamenne:Location = { Location("Marche-en-Famenne") }
    def mariakerke:Location      = { Location("Mariakerke") }
    def marcinelle:Location      = { Location("Marcinelle") }
    def meerbeke:Location        = { Location("Merebeke") }
    def molenbeek:Location       = { Location("Molenbeek") }
    def mons:Location            = { Location("Mons") }
    def mouscron:Location        = { Location("Mouscron") }
 
    def namur:Location = { Location("Namur") }

    def oudenaarde:Location = { Location("Oudenaarde") }

    def perwez:Location = { Location("Perwez") }

    def rochefort:Location = { Location("Rochefort") }
    def rocourt:Location   = { Location("Rocourt") }

    def seraing:Location           = { Location("Seraing") }
    def sintNiklaas:Location       = { Location("Sint-Niklaas") }
    def sintPietersWoluwe:Location = { Location("Sint-Pieters-Woluwe") }
    def spa:Location               = { Location("Spa") }

    def tournai:Location = { Location("Tournai") }

    def verviers:Location = { Location("Verviers") }

    def vise:Location = { Location("Vise") }

    def wanze:Location    = { Location("Wanze") }
    def waregem:Location  = { Location("Waregem") }
    def waterloo:Location = { Location("Waterloo") }
    def wetteren:Location = { Location("Wetteren") }
    def wevelgem:Location = { Location("Wevelgem") }

    def ypres:Location = { Location("Ypres") }
}

object FrenchLocations {

    implicit val country:Country = France

    def abbeville:Location = { Location("Abbeville") }
    def agde:Location = { Location("Agde") }
    def agen:Location = { Location("Agen") }
    def aigurande:Location = { Location("Aigurande") }
    def aime:Location = { Location("Aime") }
    def aixEnProvence:Location = { Location("Aix-en-Provence") }
    def aixLesBains:Location = { Location("Aix-les-Bains") }
    def ajaccio:Location = { Location("Ajaccio") }
    def albertville:Location = { Location("Albertville") }
    def albi:Location = { Location("Albi") }
    def alencon:Location = { Location("Alencon") }
    def ales:Location = { Location("Ales") }
    def alfortville:Location = { Location("Alfortville") }
    def altkirch:Location = { Location("Altkirch") }
    def alpeDHuez:Location = { Location("Alpe d'Huez", Some(1850)) }
    def amiens:Location = { Location("Amiens") }
    def ancenis:Location = { Location("Ancenis") }
    def angers:Location = { Location("Angers") }
    def angouleme:Location = { Location("Angoulême") }
    def annecy:Location = { Location("Annecy") }
    def annemasse:Location = { Location("Annemasse") }
    def annonayDavezieux:Location = { Location("Annonay-Davezieux") }
    def antibes:Location = { Location("Antibes") }
    def antonyParcDeSceaux:Location = { Location("Antony/Parc de Sceaux") }
    def arbois:Location = { Location("Arbois") }
    def arcEtSenans:Location = { Location("Arc-et-Senans") }
    def arcachon:Location = { Location("Arcachon") }
    def arenbergPorteDuHainaut:Location = { Location("Arenberg Porte du Hainaut") }
    def argelesGazost:Location = { Location("Argeles-Gazost") }
    def argelesSurMer:Location = { Location("Argelès-sur-Mer") }
    def argentan:Location = { Location("Argentan") }
    def argenteuil:Location = { Location("Argenteuil") }
    def ariege:Location = { Location("Ariege") }
    def armentieres:Location = { Location("Armentieres") }
    def arpajon:Location = { Location("Arpajon") }
    def arpajonSurCere:Location = { Location("Arpajon-sur-Cere") }
    def arras:Location = { Location("Arras") }
    def aubagne:Location = { Location("Aubagne") }
    def aubenas:Location = { Location("Aubenas") }
    def aubisque:Location = { Location("Aubisque") }
    def auch:Location = { Location("Auch") }
    def aulay:Location = { Location("Aulay") }
    def aulnaySousBois:Location = { Location("Aulnay-sous-Bois") }
    def aurillac:Location = { Location("Aurillac") }
    def autrans:Location = { Location("Autrans") }
    def autun:Location = { Location("Autun") }
    def auxerre:Location = { Location("Auxerre") }
    def avesnesSurHelpe:Location = { Location("Avesnes-sur-Helpe") }
    def avignon:Location = { Location("Avignon") }
    def avoriaz:Location = { Location("Avoriaz", Some(1800)) }
    def avranches:Location = { Location("Avranches") }
    def axLesThermes:Location = { Location("Ax-les-Thermes") }

    def bagneresDeBigorre:Location = { Location("Bagnères-de-Bigorre") }
    def bagneresDeLuchon:Location = { Location("Bagnères-de-Luchon") }
    def bagnolesDeLOrne:Location = { Location("Bagnoles-de-l'Orne") }
    def ballonDAlsace = Location("Ballon d'Alsace", Some(1178))
    def barcelonette:Location = { Location("Barcelonnette") }
    def barLeDuc:Location = { Location("Bar-le-Duc") }
    def bastia:Location = { Location("Bastia") }
    def bayonne:Location = { Location("Bayonne") }
    def bazas:Location = { Location("Bazas") }
    def beauvais:Location = { Location("Beauvais") }
    def bedoin:Location = { Location("Bedoin") }
    def belfort:Location = { Location("Belfort") }
    def bellegardeSueValserine:Location = { Location("Bellegarde-sue-Valserine") }
    def belleville:Location = { Location("Belleville") }
    def bergerac:Location = { Location("Bergerac") }
    def besancon:Location = { Location("Besançon") }
    def besse:Location = { Location("Besse") }
    def besseEnChandesse:Location = { Location("Besse-en-Chandesse") }
    def bethune:Location = { Location("Bethune") }
    def beziers:Location = { Location("Beziers") }
    def biarritz:Location = { Location("Biarritz") }
    def blagnac:Location = { Location("Blagnac") }
    def blain:Location = { Location("Blain") }
    def blayeLesMines:Location = { Location("Blaye-les-Mines") }
    def blois:Location = { Location("Blois") }
    def bobigny:Location = { Location("Bobigny") }
    def bondy:Location = { Location("Bondy") }
    def bonneval:Location = { Location("Bonneval") }
    def bordeaux:Location = { Location("Bordeaux") }
    def boulogneBillancourt:Location = { Location("Boulogne-Billancourt") }
    def boulogneSurMer:Location = { Location("Boulogne-sur-Mer") }
    def bourgDePeage:Location = { Location("Bourg-de-Peage") }
    def bourgEnBresse:Location = { Location("Bourg-en-Bresse") }
    def bourgLesValence:Location = { Location("Bourg-lès-Valence") }
    def bourgMadame:Location = { Location("Bourg-Madame") }
    def bourgSaintAndeol:Location = { Location("Bourg-Saint-Andeol") }
    def bourgSaintMaurice:Location = { Location("Bourg-Saint-Maurice") }
    def bourges:Location = { Location("Bourges") }
    def bourgoin:Location = { Location("Bourgoin") }
    def bourgoinJallieu:Location = { Location("Bourgoin-Jallieu") }
    def brest:Location = { Location("Brest") }
    def bretignySurOrge:Location = { Location("Bretigny-sur-Orge") }
    def briancon:Location = { Location("Briançon") }
    def brignoles:Location = { Location("Brignoles") }
    def brioude:Location = { Location("Brioude") }
    def brive:Location = { Location("Brive") }
    def briveLaGaillarde:Location = { Location("Brive-la-Gaillarde") }
    def bron:Location = { Location("Bron") }
    def brou:Location = { Location("Brou") }

    def caen:Location = { Location("Caen") }
    def cagnesSurMer:Location = { Location("Cagnes-sur-Mer") }
    def cahors:Location = { Location("Cahors") }
    def calais:Location = { Location("Calais") }
    def calvi:Location = { Location("Calvi") }
    def camboLesBains:Location = { Location("Cambo-les-Bains") }
    def cambrai:Location = { Location("Cambrai") }
    def cancale:Location = { Location("Cancale") }
    def cannes:Location = { Location("Cannes") }
    def capDAgde:Location = { Location("Cap d'Agde") }
    def capDAgne:Location = { Location("Cap d'Agne") }
    def capDecouverte:Location = { Location("Cap Decouverte") }
    def capFrehel:Location = { Location("Cap Frehel") }
    def captieux:Location = { Location("Captieux") }
    def carcassonne:Location = { Location("Carcassonne") }
    def carhaix:Location = { Location("Carhaix") }
    def carmaux:Location = { Location("Carmaux") }
    def carnonPlage:Location = { Location("Carnon-Plage") }
    def carpentras:Location = { Location("Carpentras") }
    def castelnaudary:Location = { Location("Castelnaudary") }
    def castelsarrasin:Location = { Location("Castelsarrasin") }
    def castillonLaBataille:Location = { Location("Castillon-la-Bataille") }
    def castres:Location = { Location("Castres") }
    def cauterets:Location = { Location("Cauterets", Some(1320)) }
    def cergyPontoise:Location = { Location("Cergy-Pontoise") }
    def cerilly:Location = { Location("Cerilly") }
    def chablis:Location = { Location("Chablis") }
    def chaletReynard:Location = { Location("Chalet Reynard (Mont Ventoux)") }
    def challans:Location = { Location("Challans") }
    def chalonSurSaone:Location = { Location("Chalon-sur-Saône") }
    def chalonsSurMarne:Location = { Location("Châlons-sur-Marne") }
    def chambery:Location = { Location("Chambery") }
    def chambord:Location = { Location("Chambord") }
    def chamonix:Location = { Location("Chamonix") }
    def champagnole:Location = { Location("Champagnole") }
    def chamrousse:Location = { Location("Chamrousse", Some(1730)) }
    def chaumont:Location = { Location("Chaumont") }
    def chantilly:Location = { Location("Chantilly") }
    def chantonnay:Location = { Location("Chantonnay") }
    def charleville:Location = { Location("Charleville") }
    def charlevilleMezieres:Location = { Location("Charleville-Mezieres") }
    def chartres:Location = { Location("Chartres") }
    def chassieu:Location = { Location("Chassieu") }
    def chateauThierry:Location = { Location("Chateau-Thierry") }
    def chateaubriant:Location = { Location("Chateaubriant") }
    def chateaulin:Location = { Location("Châteaulin") }
    def chateauroux:Location = { Location("Chateauroux") }
    def chatel:Location = { Location("Châtel") }
    def chatelGuyon:Location = { Location("Chatel-Guyon") }
    def chatellerault:Location = { Location("Chatellerault") }
    def chatou:Location = { Location("Chatou") }
    def chaumeil:Location = { Location("Chaumeil") }
    def chaville:Location = { Location("Chaville") }
    def chazeySurAin:Location = { Location("Chazey-sur-Ain") }
    def cherbourg:Location = { Location("Cherbourg") }
    def cherbourgEnCotentin:Location = { Location("Cherbourg-en-Cotentin") }
    def cholet:Location = { Location("Cholet") }
    def chorges:Location = { Location("Chorges") }
    def ciney:Location = { Location("Ciney") }
    def circuitDesEssarts:Location = { Location("Circuit des Essarts") }
    def circuitDeRouenLesEssarts:Location = { Location("Circuit de Rouen-Les-Essarts") }
    def circuitDeLaPrairie:Location = { Location("Circuit de la Prairie") }
    def clermontFerrand:Location = { Location("Clermont-Ferrand") }
    def cluses:Location = { Location("Cluses") }
    def cognac:Location = { Location("Cognac") }
    def colmar:Location = { Location("Colmar") }
    def colomiers:Location = { Location("Colomiers") }
    def commercy:Location = { Location("Commercy") }
    def compiegne:Location = { Location("Compiegne") }
    def concarneau:Location = { Location("Concarneau") }
    def corbeilEssonnes:Location = { Location("Corbeil-Essonnes") }
    def correze:Location = { Location("Correze") }
    def cosneSurLoire:Location = { Location("Cosne-sur-Loire") }
    def courchevel:Location = { Location("Courchevel", Some(2004)) }
    def creteil:Location = { Location("Creteil") }
    def cugnaux:Location = { Location("Cugnaux") }
    def culoz:Location = { Location("Culoz") }

    def damazan:Location = { Location("Damazan") }
    def dax:Location = { Location("Dax") }
    def deauville:Location = { Location("Deauville") }
    def dieppe:Location = { Location("Dieppe") }
    def digne:Location = { Location("Digne") }
    def digneLesBains:Location = { Location("Digne-les-Bains") }
    def dijon:Location = { Location("Dijon") }
    def dinan:Location = { Location("Dinan") }
    def dinard:Location = { Location("Dinard") }
    def disneylandParis:Location = { Location("Disneyland Paris") }
    def divonneLesBains:Location = { Location("Divonne-les-Bains") }
    def dole:Location = { Location("Dole") }
    def domaineDuRouret:Location = { Location("Domaine du Rouret") }
    def dordogne:Location = { Location("Dordogne") }
    def douai:Location = { Location("Douai") }
    def draguignan:Location = { Location("Draguignan") }
    def dreux:Location = { Location("Dreux") }
    def drome:Location = { Location("Drome") }
    def dunkerque:Location = { Location("Dunkerque") }

    def embrun:Location = { Location("Embrun") }
    def epernay:Location = { Location("Epernay") }
    def epinal:Location = { Location("Epinal") }
    def epnaySousSenart:Location = { Location("Epnay-sous-Senart") }
    def espelette:Location = { Location("Espelette") }
    def etampes:Location = { Location("Etampes") }
    def eurotunnel:Location = { Location("Eurotunnel") }
    def evian:Location = { Location("Evian") }
    def evianLesBains:Location = { Location("Evian-les-Bains") }
    def evreux:Location = { Location("Evreux") }
    def evry:Location = { Location("Evry") }
    def eymet:Location = { Location("Eymet") }

    def faverges:Location = { Location("Faverges") }
    def fecamp:Location = { Location("Fecamp") }
    def figeac:Location = { Location("Figeac") }
    def flers:Location = { Location("Flers") }
    def fleurance:Location = { Location("Fleurance") }
    def foix:Location = { Location("Foix") }
    def fontRomeuOdeilloVia:Location = { Location("Font-Romeu-Odeillo-Via") }
    def fontaine:Location = { Location("Fontaine") }
    def fontaineAuPire:Location = { Location("Fontaine-au-Pire") }
    def fontainebleau:Location = { Location("Fontainebleau") }
    def fontenayLeComte:Location = { Location("Fontenay-le-Comte") }
    def fontenaySousBois:Location = { Location("Fontenay-sous-Bois") }
    def forgesLesEaux:Location = { Location("Forges-les-Eaux") }
    def fougeres:Location = { Location("Fougeres") }
    def fougres:Location = { Location("Fougres") }
    def fromentine:Location = { Location("Fromentine") }
    def frontenex:Location = { Location("Frontenex") }
    def frontignanLaPeyrade:Location = { Location("Frontignan la Peyrade") }
    def futuroscope:Location = { Location("Futuroscope") }

    def gaillac:Location = { Location("Gaillac") }
    def gaillard:Location = { Location("Gaillard") }
    def gap:Location = { Location("Gap") }
    def gerardmer:Location = { Location("Gerardmer") }
    def gerardmerLasMauselaine:Location = { Location("Gerardmer las Mauselaine") }
    def gex:Location = { Location("Gex") }
    def givors:Location = { Location("Givors") }
    def gourette:Location = { Location("Gourette") }
    def gouretteColDAubisque:Location = { Location("Gourette-Col d'Aubisque") }
    def granville:Location = { Location("Granville") }
    def grenoble:Location = { Location("Grenoble") }
    def gruissan:Location = { Location("Gruissan") }
    def gueret:Location = { Location("Gueret") }
    def gueugnon:Location = { Location("Gueugnon") }
    def guillestre:Location = { Location("Guillestre") }
    def guzetNeige:Location = { Location("Guzet-Neige", Some(1480)) }

    def hendaye:Location = { Location("Hendaye") }
    def houilles:Location = { Location("Houilles") }
    def hyeres:Location = { Location("Hyeres") }

    def ileDOleron:Location = { Location("Ile d'Oleron") }
    def isola:Location = { Location("Isola") }
    def issoire:Location = { Location("Issoire") }
    def issoudun:Location = { Location("Issoudun") }

    def jaunayClan:Location = { Location("Jaunay-Clan") }
    def jausiers:Location = { Location("Jausiers") }
    def joigny:Location = { Location("Joigny") }
    def joinville:Location = { Location("Joinville") }
    def jonzac:Location = { Location("Jonzac") }

    def lIsleDAbeau:Location = { Location("L'Isle-d'Abeau") }
    def lIsleJourdain:Location = { Location("L'Isle-Jourdain") }
    def laBaule:Location = { Location("La Baule") }
    def leBourgDOisans:Location = { Location("Le Bourg-d'Oisans") }
    def laCaverneDuPontDArc:Location = { Location("La Caverne du Pont-d'Arc") }
    def laChataigneraie:Location = { Location("La Chataigneraie") }
    def laChatre:Location = { Location("La Chatre") }
    def laDefense:Location = { Location("La Defense") }
    def laFerteSousJouarre:Location = { Location("La Ferte-sous-Jouarre") }
    def laFouillouse:Location = { Location("La Fouillouse") }
    def laGrandeMotte:Location = { Location("La Grande-Motte") }
    def laGuercheDeBretagne:Location = { Location("La Guerche-de-Bretagne") }
    def laHaieFouassiere:Location = { Location("La Haie-Fouassiere") }
    def laLoupe:Location = { Location("La Loupe") }
    def laMongie:Location = { Location("La Mongie", Some(1715)) }
    def laMure:Location = { Location("La Mure") }
    def laPlagne:Location = { Location("La Plagne", Some(1970)) }
    def laRocheSurYon:Location = { Location("La Roche-sur-Yon") }
    def laRochelle:Location = { Location("La Rochelle") }
    def laRosiere:Location = { Location("La Rosiere", Some(1855)) }
    def laTourDuPin:Location = { Location("La Tour-du-Pin") }
    def laToussuire:Location = { Location("La Toussuire", Some(1705)) }
    def laToussuireLesSybelles:Location = { Location("La Toussuire - Les Sybelles", Some(1705)) }
    def labastideDArmagnac:Location = { Location("Labastide-d'Armagnac") }
    def lacanau:Location = { Location("Lacanau") }
    def lacDeMadine:Location = { Location("Lac de Madine") }
    def lacDePayolle:Location = { Location("Lac de Payolle") }
    def lacDeVassiviere:Location = { Location("Lac de Vassiviere") }
    def lacSaintPoint:Location = { Location("Lac Saint-Point") }
    def laissacSeveracLEglise:Location = { Location("Laissac-Severac-l'Eglise") }
    def lamballe:Location = { Location("Lamballe") }
    def lanester:Location = { Location("Lanester") }
    def langon:Location = { Location("Langon") }
    def lannemezan:Location = { Location("Lannemezan") }
    def lannion:Location = { Location("Lannion") }
    def lansEnVercors:Location = { Location("Lans-en-Vercors", Some(1410)) }
    def laon:Location = { Location("Laon") }
    def laplume:Location = { Location("Laplume") }
    def laruns:Location = { Location("Laruns") }
    def laval:Location = { Location("Laval") }
    def lavalanet:Location = { Location("Lavalanet") }
    def lavaur:Location = { Location("Lavaur") }
    def lavelanet:Location = { Location("Lavelanet") }
    def leBarcares:Location = { Location("Le Barcarès") }
    def leBettex:Location = { Location("Le Bettex, Saint-Gervais - Mont Blanc", Some(1372)) }
    def leBlanc:Location = { Location("Le Blanc") }
    def leCreusot:Location = { Location("Le Creusot") }
    def leGrandBornand:Location = { Location("Le Grand Bornand") }
    def leHavre:Location = { Location("Le Havre") }
    def leMans:Location = { Location("Le Mans") }
    def leMonetierLesBains:Location = { Location("Le Monetier-les-Bains") }
    def lePerreuxSurMarne:Location = { Location("Le Perreux-sur-Marne") }
    def lePleynet = Location("Le Pleynet")
    def lePuy:Location = { Location("Le Puy") }
    def lePuyDuFou:Location = { Location("Le Puy du Fou") }
    def lePuyEnVelay:Location = { Location("Le Puy-en-Velay") }
    def leRevard:Location = { Location("Le Revard") }
    def leTouquet:Location = { Location("Le Touquet") }
    def leTouquetParisPlage:Location = { Location("Le Touquet-Paris-Plage") }
    def leTreport:Location = { Location("Le Treport") }
    def lesArcs:Location = { Location("Les Arcs", Some(1700)) }
    def lesDeuxAlpes:Location = { Location("Les Deux Alpes", Some(1644)) }
    def lesEchelles:Location = { Location("Les Echelles") }
    def lesEssarts:Location = { Location("Les Essarts") }
    def lesMenuires:Location = { Location("Les Menuires", Some(1809)) }
    def lesSablesDOlonne:Location = { Location("Les Sables-d'Olonne") }
    def levalloisPerret:Location = { Location("Levallois-Perret") }
    def lezatSurLeze:Location = { Location("Lezat-sur-Leze") }
    def lezignanCorbieres:Location = { Location("Lezignan-Corbieres") }
    def libourne:Location = { Location("Libourne") }
    def lievin:Location = { Location("Lievin") }
    def lille:Location = { Location("Lille") }
    def lilleMetropole:Location = { Location("Lille Metropole") }
    def limoges:Location = { Location("Limoges") }
    def limoux:Location = { Location("Limoux") }
    def lisieux:Location = { Location("Lisieux") }
    def livarot:Location = { Location("Livarot") }
    def lodeve:Location = { Location("Lodève") }
    def longjumeau:Location = { Location("Longjumeau") }
    def longwy:Location = { Location("Longwy") }
    def lonsLeSaunier:Location = { Location("Lons-le-Saunier") }
    def lorient:Location = { Location("Lorient") }
    def loudenvielle:Location = { Location("Loudenvielle") }
    def loudon:Location = { Location("Loudon") }
    def louhansChateaurenaud:Location = { Location("Louhans-Chateaurenaud") }
    def lourdes:Location = { Location("Lourdes") }
    def louvroil:Location = { Location("Louvroil") }
    def luchon:Location = { Location("Luchon") }
    def lucon:Location = { Location("Lucon") }
    def lugny:Location = { Location("Lugny") }
    def luneville:Location = { Location("Luneville") }
    def luzArdiden:Location = { Location("Luz Ardiden", Some(1715)) }
    def luzSaintSauveur:Location = { Location("Luz-Saint-Sauveur") }
    def lyon:Location = { Location("Lyon") }

    def machecoul:Location = { Location("Machecoul") }
    def macon:Location = { Location("Macon") }
    def maloLesBains:Location = { Location("Malo-les-Bains") }
    def manosque:Location = { Location("Manosque") }
    def marcoussis:Location = { Location("Marcoussis") }
    def marennes:Location = { Location("Marennes") }
    def marseille:Location = { Location("Marseille") }
    def martigues:Location = { Location("Martigues") }
    def mauberge:Location = { Location("Mauberge") }
    def maubourguetPaysDuValDAdour:Location = { Location("Maubourguet Pays du Val d'Adour") }
    def mayenne:Location = { Location("Mayenne") }
    def mazamet:Location = { Location("Mazamet") }
    def mazeMontgeoffroy:Location = { Location("Maze-Montgeoffroy") }
    def meaux:Location = { Location("Meaux") }
    def megeve:Location = { Location("Megeve") }
    def melun:Location = { Location("Melun") }
    def mende:Location = { Location("Mende") }
    def menton:Location = { Location("Menton") }
    def merlinPlage:Location = { Location("Merlin-Plage") }
    def mersLesBains:Location = { Location("Mers-les-Bains") }
    def metz:Location = { Location("Metz") }
    def meudon:Location = { Location("Meudon") }
    def meyrignacLEglise:Location = { Location("Meyrignac-l'Eglise") }
    def millau:Location = { Location("Millau") }
    def miramas:Location = { Location("Miramas") }
    def modane:Location = { Location("Modane") }
    def moiransEnMontagne:Location = { Location("Moirans-en-Montagne") }
    def montDeMarsan:Location = { Location("Mont-de-Marsan") }
    def montDesAlouettes:Location = { Location("Mont des Alouettes") }
    def montSaintMichel:Location = { Location("Mont Saint-Michel") }
    def montaigu:Location = { Location("Montaigu") }
    def montargis:Location = { Location("Montargis") }
    def montauban:Location = { Location("Montauban") }
    def montbeliard:Location = { Location("Montbeliard") }
    def montbrison:Location = { Location("Montbrison") }
    def montceauLesMines:Location = { Location("Montceau-les-Mines") }
    def montelimar:Location = { Location("Montelimar") }
    def montereauFaultYonne:Location = { Location("Montereau-Fault-Yonne") }
    def montgeron:Location = { Location("Montgeron") }
    def montlhery:Location = { Location("Montlhery") }
    def montlucon:Location = { Location("Montlucon") }
    def montpellier:Location = { Location("Montpellier") }
    def montponMenesterol:Location = { Location("Montpon-Menesterol") }
    def montreuil:Location = { Location("Montreuil") }
    def montVentoux:Location = { Location("Mont Ventoux", Some(1912)) }
    def morcenx:Location = { Location("Morcenx") }
    def morlaix:Location = { Location("Morlaix") }
    def morzine:Location = { Location("Morzine") }
    def morzineAvoriaz:Location = { Location("Morzine-Avoriaz") }
    def mouilleronSaintGermain:Location = { Location("Mouilleron-Saint-Germain") }
    def mourenx:Location = { Location("Mourenx") }
    def moutiers:Location = { Location("Moûtiers") }
    def mulhouse:Location = { Location("Mulhouse") }
    def muret:Location = { Location("Muret") }

    def nancy:Location = { Location("Nancy") }
    def nanterre:Location = { Location("Nanterre") }
    def nantes:Location = { Location("Nantes") }
    def nantua:Location = { Location("Nantua") }
    def narbonne:Location = { Location("Narbonne") }
    def nay:Location = { Location("Nay") }
    def nemours:Location = { Location("Nemours") }
    def neufchatelEnBray:Location = { Location("Neufchatel-en-Bray") }
    def neuvilleDePoitou:Location = { Location("Neuville-de-Poitou") }
    def nevers:Location = { Location("Nevers") }
    def nice:Location = { Location("Nice") }
    def nimes:Location = { Location("Nîmes") }
    def niort:Location = { Location("Niort") }
    def nogentSurMarne:Location = { Location("Nogent-sur-Marne") }
    def nogentSurOise:Location = { Location("Nogent-sur-Oise") }
    def noirmoutierEnLIle:Location = { Location("Noirmoutier-en-l'Île") }
    def noisyLeSec:Location = { Location("Noisy-le-Sec") }
    def nuitsSaintGeorges:Location = { Location("Nuits-Saint-Georges") }

    def obernai:Location = { Location("Obernai") }
    def olonneSurMer:Location = { Location("Olonne-sur-Mer") }
    def oloronSainteMarie:Location = { Location("Oloron-Sainte-Marie") }
    def orange:Location = { Location("Orange") }
    def orcieresMerlette:Location = { Location("Orcières-Merlette", Some(1838)) }
    def orchies:Location = { Location("Orchies") }
    def orleans:Location = { Location("Orléans") }
    def orsonville:Location = { Location("Orsonville") }
    def orthez:Location = { Location("Orthez") }
    def oyonnax:Location = { Location("Oyonnax") }

    def palaiseau:Location = { Location("Palaiseau") }
    def pamiers:Location = { Location("Pamiers") }
    def pantin:Location = { Location("Pantin") }
    def paris:Location = { Location("Paris") }
    def passageDuGois:Location = { Location("Passage du Gois") }
    def pau:Location = { Location("Pau") }
    def pauillac:Location = { Location("Pauillac") }
    def perigueux:Location = { Location("Périgueux") }
    def peronne:Location = { Location("Peronne") }
    def perpignan:Location = { Location("Perpignan") }
    def perrosGuirec:Location = { Location("Perros-Guirec") }
    def peyrehorade:Location = { Location("Peyrehorade") }
    def plaDAdet:Location = { Location("Pla d'Adet") }
    def plouay:Location = { Location("Plouay") }
    def plumelec:Location = { Location("Plumelec") }
    def poitiers:Location = { Location("Poitiers") }
    def pontAudemer:Location = { Location("Pont-Audemer") }
    def pontDeVaux:Location = { Location("Pont-de-Vaux") }
    def pontLEveque:Location = { Location("Pont l'Eveque") }
    def pontarlier:Location = { Location("Pontarlier") }
    def pontchateau:Location = { Location("Pontchateau") }
    def pontoise:Location = { Location("Pontoise") }
    def pornic:Location = { Location("Pornic") }
    def pornichet:Location = { Location("Pornichet") }
    def porrentruy:Location = { Location("Porrentruy") }
    def porteMaillot:Location = { Location("Porte Maillot, Paris") }
    def portoVecchio:Location = { Location("Porto-Vecchio") }
    def pouillyEnAuxois:Location = { Location("Pouilly-en-Auxois") }
    def prades:Location = { Location("Prades") }
    def praLoup:Location = { Location("Pra-Loup", Some(1630)) }
    def prapoutel:Location = { Location("Prapoutel") }
    def privas:Location = { Location("Privas") }
    def provence:Location = { Location("Provence") }

    def quimper:Location = { Location("Quimper") }

    def rambouillet:Location = { Location("Rambouillet") }
    def redon:Location = { Location("Redon") }
    def regnieDurette:Location = { Location("Regnie-Durette") }
    def reims:Location = { Location("Reims") }
    def renaze:Location = { Location("Renaze") }
    def rennes:Location = { Location("Rennes") }
    def revel:Location = { Location("Revel") }
    def risoul:Location = { Location("Risoul", Some(1855)) }
    def roanne:Location = { Location("Roanne") }
    def rochefort:Location = { Location("Rochefort") }
    def rodez:Location = { Location("Rodez") }
    def romansSurIsere:Location = { Location("Romans-sur-Isere") }
    def roquefortSurSoulzon:Location = { Location("Roquefort-sur-Soulzon") }
    def roscoff:Location = { Location("Roscoff") }
    def rossignolVoiron:Location = { Location("Rossignol Voiron") }
    def roubaix:Location = { Location("Roubaix") }
    def rouen:Location = { Location("Rouen") }
    def royan:Location = { Location("Royan") }
    def ruelleSurTourve:Location = { Location("Ruelle sur Tourve") }
    def ruffex:Location = { Location("Ruffex") }
    def rungis:Location = { Location("Rungis") } 

    def sableSurSarthe:Location = { Location("Sablé-sur-Sarthe") }
    def saintAmandLesEaux:Location = { Location("Saint-Amand-les-Eaux") }
    def saintAmandMontrond:Location = { Location("Saint-Amand-Montrond") }
    def saintArnoultEnYvelines:Location = { Location("Saint-Arnoult-en-Yvelines") }
    def saintBrieuc:Location = { Location("Saint-Brieuc") }
    def saintDenis:Location = { Location("Saint-Denis") }
    def saintDierDAuvergne:Location = { Location("Saint-Dier-d'Auvergne") }
    def saintDizier:Location = { Location("Saint-Dizier") }
    def saintEmilion:Location = { Location("Saint-Emilion") }
    def saintEtienne:Location = { Location("Saint-Étienne") }
    def saintFargeau:Location = { Location("Saint-Fargeau") }
    def saintFlour:Location = { Location("Saint-Flour") }
    def saintFrancoisLongchamp:Location = { Location("Saint-François-Longchamp") }
    def saintGalmier:Location = { Location("Saint Galmier") }
    def saintGaudens:Location = { Location("Saint-Gaudens") }
    def saintGermain:Location = { Location("Saint-Germain") }
    def saintGermainEnLaye:Location = { Location("Saint-Germain-en-Laye") }
    def saintGervais:Location = { Location("Saint-Gervais") }
    def saintGervaisMontBlanc:Location = { Location("Saint-Gervais Mont-Blanc", Some(970)) }
    def saintGervaisLesBains:Location = { Location("Saint Gervais-les-Bains") }
    def saintGildasDesBois:Location = { Location("Saint-Gildas-des-Bois") }
    def saintGillesCroixDeVie:Location = { Location("Saint-Gilles-Croix-de-Vie") }
    def saintGirons:Location = { Location("Saint-Girons") }
    def saintGregoire:Location = { Location("Saint Gregoire") }
    def saintHerblain:Location = { Location("Saint-Herblain") }
    def saintHilaireDuHarcouet:Location = { Location("Saint-Hilaire-du-Harcouët") }
    def saintJeandDeMaurienne:Location = { Location("Saint-Jean-de-Maurienne") }
    def saintJeanDeMonts:Location = { Location("Saint-Jean-de-Monts") }
    def saintJulienEnGenevois:Location = { Location("Saint-Julien-en-Genevois") }
    def saintJustSaintRambert:Location = { Location("Saint-Just-Saint-Rambert") }
    def saintLaryPlaDAdet:Location = { Location("Saint-Lary Pla d'Adet") }
    def saintLarySoulan:Location = { Location("Saint-Lary-Soulan") }
    def saintLarySoulanPlaDAdet:Location = { Location("Saint-Lary-Soulan Pla d'Adet", Some(1680)) }
    def saintLeonardDeNoblat:Location = { Location("Saint-Leonard-de-Noblat") }
    def saintLo:Location = { Location("Saint-Lo") }
    def saintMaixentLEcole:Location = { Location("Saint-Maixent-l'Ecole") }
    def saintMalo:Location = { Location("Saint-Malo") }
    def saintMartinDeLandelles:Location = { Location("Saint-Martin-de-Landelles") }
    def saintMeenLeGrand:Location = { Location("Saint-Meen-le-Grand") }
    def saintNazaire:Location = { Location("Saint-Nazaire") }
    def saintOmer:Location = { Location("Saint-Omer") }
    def saintOrensDeGameville:Location = { Location("Saint-Orens-de-Gameville") }
    def saintPaulTroisChateaux:Location = { Location("Saint-Paul-Trois-Chateaux") }
    def saintPeeSurNivelle:Location = { Location("Saint-Pée-sur-Nivelle") }
    def saintPolDeLeon:Location = { Location("Saint-Pol-de-Léon") }
    def saintpourcainSurSioule:Location = { Location("Saint-Pourcain-sur-Sioule") }
    def saintPriest:Location = { Location("Saint-Priest") }
    def saintQuentin:Location = { Location("Saint-Quentin") }
    def saintQuentinEnYvelines:Location = { Location("Saint-Quentin-en-Yvelines") }
    def saintRaphael:Location = { Location("Saint-Raphael") }
    def saintTrivierSurMoignans:Location = { Location("Saint-Trivier-sur-Moignans") }
    def saintValeryEnCaux:Location = { Location("Saint-Valery-en-Caux") }
    def sainteFoyLaGrande:Location = { Location("Sainte-Foy-la-Grande") }
    def sainteGenevieveDesBois:Location = { Location("Sainte-Genevieve-des-Bois") }
    def saintes:Location = { Location("Saintes") }
    def saliesDeBearn:Location = { Location("Salies-de-Bearn") }
    def sallanches:Location = { Location("Sallanches") }
    def salonDeProvence:Location = { Location("Salon-de-Provence") }
    def samatan:Location = { Location("Samatan") }
    def santennay:Location = { Location("Santennay") }
    def sarran:Location = { Location("Sarran") }
    def sarrebourg:Location = { Location("Sarrebourg") }
    def sarzeau:Location = { Location("Sarzeau") }
    def saumur:Location = { Location("Saumur") }
    def sauternes:Location = { Location("Sauternes") }
    def savinesLeLac:Location = { Location("Savines-le-Lac") }
    def sceaux:Location = { Location("Sceaux") }
    def sedan:Location = { Location("Sedan") }
    def seignosseLePenon:Location = { Location("Seignosse le Penon") }
    def semnoz:Location = { Location("Semnoz") }
    def semurEnAuxois:Location = { Location("Semur-en-Auxois") }
    def senlis:Location = { Location("Senlis") }
    def sens:Location = { Location("Sens") }
    def serreChevalier:Location = { Location("Serre Chevalier", Some(1200)) }
    def sete:Location = { Location("Sete") }
    def seurre:Location = { Location("Seurre") }
    def sevres:Location = { Location("Sevres") }
    def sisteron:Location = { Location("Sisteron") }
    def soissons:Location = { Location("Soissons") }
    def stationDesRousses:Location = { Location("Station des Rousses") }
    def strasbourg:Location = { Location("Strasbourg") }
    def suresnes:Location = { Location("Suresnes, Paris") }

    def tallard:Location = { Location("Tallard") }
    def tarasconSurAriege:Location = { Location("Tarascon-sur-Ariege") }
    def tarbes:Location = { Location("Tarbes") }
    def thionville:Location = { Location("Thionville") }
    def thononLesBains:Location = { Location("Thonon-les-Bains") }
    def thuir:Location = { Location("Thuir") }
    def tignes:Location = { Location("Tignes") }
    def tomblaine:Location = { Location("Tomblaine") }
    def tonnerre:Location = { Location("Tonnerre") }
    def toulon:Location = { Location("Toulon") }
    def toulouse:Location = { Location("Toulouse") }
    def tournus:Location = { Location("Tournus") }
    def tours:Location = { Location("Tours") }
    def trelissac:Location = { Location("Trelissac") }
    def trets:Location = { Location("Trets") }
    def trieSurBasie:Location = { Location("Trie-sur-Basie") }
    def trouville:Location = { Location("Trouville") }
    def troyes:Location = { Location("Troyes") }
    def tulle:Location = { Location("Tulle") }

    def utahBeach:Location = { Location("Utah Beach (Sainte-Marie-du-Mont)") }

    def vaisonLaRromaine:Location = { Location("Vaison-la-Romaine") }
    def valDIsere:Location = { Location("Val d'Isère", Some(1820)) }
    def valLouron:Location = { Location("Val Louron") }
    def valThorens:Location = { Location("Val Thorens", Some(2275)) }
    def valence:Location = { Location("Valence") }
    def valenceDAgen:Location = { Location("Valence d'Agen") }
    def valenciennes:Location = { Location("Valenciennes") }
    def valentigney:Location = { Location("Valentigney") }
    def valloire:Location = { Location("Valloire") }
    def valmorel:Location = { Location("Valmorel") }
    def valreas:Location = { Location("Valreas") }
    def valsLesBains:Location = { Location("Vals-les-Bains") }
    def vannes:Location = { Location("Vannes") }
    def vatan:Location = { Location("Vatan") }
    def vaucluse:Location = { Location("Vaucluse") }
    def vence:Location = { Location("Vence") }
    def vercors:Location = { Location("Lan-en-Vercors") }
    def verdun:Location = { Location("Verdun") }
    def versailles:Location = { Location("Versailles") }
    def vesoul:Location = { Location("Vesoul") }
    def veurey:Location = { Location("Veurey") }
    def vichy:Location = { Location("Vichy") }
    def vierzon:Location = { Location("Vierzon") }
    def villardDeLans:Location = { Location("Villard-de-Lans", Some(1150)) }
    def villarLesDombes:Location = { Location("Villar-les-Dombes (Parc des Oiseaux)") }
    def villeDAvray:Location = { Location("Ville-d'Avray") }
    def villefrancheSurSaone:Location = { Location("Villefranche-sur-Saone") }
    def villeneuveSurLot:Location = { Location("Villeneuve-sur-Lot") }
    def villersCotterets:Location = { Location("Villers-Cotterets") }
    def villersSurMer:Location = { Location("Villers-sur-Mer") }
    def villeurbanne:Location = { Location("Villeurbanne") }
    def villieMorgon:Location = { Location("Villié-Morgon") }
    def vire:Location = { Location("Vire") }
    def viryChatillon:Location = { Location("Viry-Chatillon") }
    def vitre:Location = { Location("Vitre") }
    def vittel:Location = { Location("Vittel") }
    def vizelle:Location = { Location("Vizelle") }
    def vouvray:Location = { Location("Vouvray") }
    def voreppe:Location = { Location("Voreppe") }

    def wasquehal:Location = { Location("Wasquehal") }

    // French cols

    def leLioran          = Location("Le Lioran", Some(1326))
    def laRuchere         = Location("La Ruchère", Some(1160))
    def puyDeDome         = Location("Puy de Dôme", Some(1415))
    def superbagneres     = Location("Superbagnères", Some(1804))
    def valdebloreLaColmiane = Location("Valdeblore La Colmiane", Some(1500))
}

object GermanLocations {

    implicit val country:Country = Germany

    def cologne:Location     = { Location("Cologne") }
    def dusseldorf:Location  = { Location("Dusseldorf") }
    def freiburg:Location    = { Location("Freiburg") }
    def koblenz:Location     = { Location("Koblenz") }
    def munster:Location     = { Location("Münster") }
    def saarbrucken:Location = { Location("Saarbrücken") }
    def pforzheim:Location   = { Location("Pforzheim") }
    def karlsruhe:Location   = { Location("Karlsruhe") }
}

object IrishLocations {

    implicit val country:Country = Ireland

    def cork:Location        = { Location("Cork") }
    def dublin:Location      = { Location("Dublin") }
    def enniscorthy:Location = { Location("Enniscorthy") }

}

object ItalianLocations {

    implicit val country:Country = Italy

    def abanoTerme:Location = { Location("Abano Terme") }
    def abbadiaSanSalvatore:Location = { Location("Abbadia San Salvatore") }
    def abbazia:Location = { Location("Abbazia") }
    def abbiategrasso:Location = { Location("Abbiategrasso") }
    def abetone:Location = { Location("Abetone", Some(1386)) }
    def acquappesa:Location = { Location("Acquappesa") }
    def acquiTerme:Location = { Location("Acqui Terme") }
    def agile:Location = { Location("Agile") }
    def agordo:Location = { Location("Agordo") }
    def agrigento:Location = { Location("Agrigento") }
    def agropoli:Location = { Location("Agropoli") }
    def alassio:Location = { Location("Alassio") }
    def alba:Location = { Location("Alba") }
    def albaAdriatica:Location = { Location("Alba Adriatica") }
    def albenga:Location = { Location("Albenga") }
    def alberobello:Location = { Location("Alberobello") }
    def albeseConCassano:Location = { Location("Albese con Cassano") }
    def alessandria:Location = { Location("Alessandria") }
    def alghero:Location = { Location("Alghero") }
    def alleghe:Location = { Location("Alleghe") }
    def alpago:Location = { Location("Alpago") }
    def alpeDiPampeago:Location = { Location("Alpe di Pampeago", Some(1983)) }
    def alpeDiSiusi:Location = { Location("Alpe di Siusi", Some(1844)) }
    def altopianoDelMontasio:Location = { Location("Altopiano del Montasio") }
    def amalfi:Location = { Location("Amalfi") }
    def amantea:Location = { Location("Amantea") }
    def amatrice:Location = { Location("Amatrice") }
    def anagi:Location = { Location("Anagi") }
    def ancona:Location = { Location("Ancona") }
    def andalo:Location = { Location("Andalo", Some(1024)) }
    def annifo:Location = { Location("Annifo", Some(895)) }
    def anterselva:Location = { Location("Anterselva", Some(1635)) }
    def aosta:Location = { Location("Aosta") }
    def aprica:Location = { Location("Aprica", Some(1173)) }
    def arabba:Location = { Location("Arabba") }
    def arco:Location = { Location("Arco") }
    def arcore:Location = { Location("Arcore") }
    def arenzano:Location = { Location("Arenzano") }
    def arezzo:Location = { Location("Arezzo") }
    def arona:Location = { Location("Arona") }
    def arosio:Location = { Location("Arosio") }
    def artaTerme:Location = { Location("Arta Terme") }
    def arzignano:Location = { Location("Arzignano") }
    def ascoliPiceno:Location = { Location("Ascoli Piceno") }
    def asiago:Location = { Location("Asiago") }
    def asolo:Location = { Location("Asolo") }
    def assisi:Location = { Location("Assisi") }
    def asti:Location = { Location("Asti") }
    def aulla:Location = { Location("Aulla") }
    def auronzoDiCadore:Location = { Location("Auronzo di Cadore") }
    def autodromoEnzoEDinoFerrari:Location = { Location("Imola (Autodromo Enzo e Dino Ferrari)") }
    def avaglio:Location = { Location("Avaglio", Some(738)) }
    def avellino:Location = { Location("Avellino") }
    def aversa:Location = { Location("Aversa") }
    def avezzano:Location = { Location("Avezzano") }

    def bacoli:Location = { Location("Bacoli") }
    def bagniDiCascianaTerme:Location = { Location("Bagni di Casciana Terme") }
    def bagnoDiRomagna:Location = { Location("Bagno di Romagna") }
    def bagnoliIirpino:Location = { Location("Bagnoli Irpino") }
    def baiaDomizia:Location = { Location("Baia Domizia") }
    def barbaresco:Location = { Location("Barbaresco") }
    def barberinoDiMugello:Location = { Location("Barberino di Mugello") }
    def bardolino:Location = { Location("Bardolino") }
    def bardonecchia:Location = { Location("Bardonecchia") }
    def bari:Location = { Location("Bari") }
    def barletta:Location = { Location("Barletta") }
    def barolo:Location = { Location("Barolo") }
    def barumini:Location = { Location("Barumini") }
    def barzio:Location = { Location("Barzio") }
    def baselgaDiPine:Location = { Location("Baselga di Pine") }
    def bassanoDelGrappa:Location = { Location("Bassano del Grappa") }
    def bellaria:Location = { Location("Bellaria") }
    def belluno:Location = { Location("Belluno") }
    def bellunoNevegal:Location = { Location("Belluno Nevegal") }
    def belvedereMarittimo:Location = { Location("Belvedere Marittimo") }
    def benevento:Location = { Location("Benevento") }
    def bergamo:Location = { Location("Bergamo") }
    def bezzecca:Location = { Location("Bezzecca") }
    def biandronno:Location = { Location("Biandronno") }
    def bibbiena:Location = { Location("Bibbiena") }
    def bibione:Location = { Location("Bibione") }
    def biella:Location = { Location("Biella") }
    def binago:Location = { Location("Binago") }
    def bitonto:Location = { Location("Bitonto") }
    def boarioTerme:Location = { Location("Boario Terme") }
    def bologna:Location = { Location("Bologna") }
    def bolsena:Location = { Location("Bolsena") }
    def bolzano:Location = { Location("Bolzano") }
    def bordighera:Location = { Location("Bordighera") }
    def borgo:Location = { Location("Borgo Val di Taro") }
    def borgoAMozzano:Location = { Location("Borgo a Mozzano") }
    def borgoSanDalmazzo:Location = { Location("Borgo San Dalmazzo") }
    def borgoValDiTaro:Location = { Location("Borgo Val di Taro") }
    def borgoValsugana:Location = { Location("Borgo Valsugana") }
    def borgomanero:Location = { Location("Borgomanero") }
    def bormio:Location = { Location("Bormio", Some(1225)) }
    def bormio2000:Location = { Location("Bormio 2000") }
    def borno:Location = { Location("Borno") }
    def bosa:Location = { Location("Bosa") }
    def boscoChiesanuova:Location = { Location("Bosco Chiesanuova") }
    def bra:Location = { Location("Bra") }
    def brentonico:Location = { Location("Brentonico") }
    def brescia:Location = { Location("Brescia") }
    def bresciaSantEufemia:Location = { Location("Brescia Sant'Eufemia") }
    def bressanone:Location = { Location("Bressanone") }
    def breuilCervinia:Location = { Location("Breuil-Cervinia") }
    def brindisi:Location = { Location("Brindisi") }
    def brixen:Location = { Location("Brixen") }
    def bruneck:Location = { Location("Bruneck") }
    def bruzzolana:Location = { Location("Bruzzolana", Some(523)) }
    def bucchianico:Location = { Location("Bucchianico") }
    def busseto:Location = { Location("Busseto") }
    def bustoArsizio:Location = { Location("Busto Arsizio") }

    def cagliari:Location = { Location("Cagliari") }
    def caldesValDiSole:Location = { Location("Caldes-Val di Sole") }
    def caltagirone:Location = { Location("Caltagirone") }
    def caltanissetta:Location = { Location("Caltanissetta") }
    def camaiore:Location = { Location("Camaiore") }
    def cambiago:Location = { Location("Cambiago") }
    def camigliatelloSilano:Location = { Location("Camigliatello Silano") }
    def campiBisenzio:Location = { Location("Campi Bisenzio") }
    def campiSalentina:Location = { Location("Campi Salentina") }
    def campioneDItalia:Location = { Location("Campione d'Italia") }
    def campitelloMatese:Location = { Location("Campitello Matese") }
    def campoDeiFiori:Location = { Location("Campo dei Fiori") }
    def campobasso:Location = { Location("Campobasso") }
    def campotenese:Location = { Location("Campotenese") }
    def canazei:Location = { Location("Canazei") }
    def canelli:Location = { Location("Canelli") }
    def cannobio:Location = { Location("Cannobio") }
    def cantu:Location = { Location("Cantu") }
    def capannori:Location = { Location("Capannori") }
    def capoDOrlando:Location = { Location("Capo d'Orlando") }
    def caprera:Location = { Location("Caprera") }
    def capua:Location = { Location("Capua") }
    def caravaggio:Location = { Location("Caravaggio") }
    def carovigno:Location = { Location("Carovigno") }
    def carpegna:Location = { Location("Carpegna") }
    def carpi:Location = { Location("Carpi") }
    def carrara:Location = { Location("Carrara") }
    def casaleMonferrato:Location = { Location("Casale Monferrato") }
    def cascataDelToce:Location = { Location("Cascata del Toce") }
    def cascia:Location = { Location("Cascia") }
    def cascianaTerme:Location = { Location("Casciana Terme") }
    def cascina:Location = { Location("Cascina") }
    def caserta:Location = { Location("Caserta") }
    def cassanoDAdda:Location = { Location("Cassano d'Adda") }
    def cassino:Location = { Location("Cassino") }
    def casteggio:Location = { Location("Casteggio") }
    def castelGandolfo:Location = { Location("Castel Gandolfo") }
    def castelfidardo:Location = { Location("Castelfidardo") }
    def castelfrancoVeneto:Location = { Location("Castelfranco Veneto") }
    def castellammareDiStabia:Location = { Location("Castellammare di Stabia") }
    def castellamonte:Location = { Location("Castellamonte") }
    def castellanaGrotte:Location = { Location("Castellana Grotte") }
    def castellania:Location = { Location("Castellania") }
    def castelnuouvoDiValDiCecina:Location = { Location("Castelnuouvo di Val di Cecina") }
    def castelraimondo:Location = { Location("Castelraimondo") }
    def castelrotto:Location = { Location( "Castelrotto" ) }
    def castigilioneDellaPescaia:Location = { Location("Castiglione della Pescaia") }
    def castiglioneDelLago:Location = { Location("Castiglione del Lago") }
    def castiglioneDellaPescaia:Location = { Location("Castiglione della Pescaia") }
    def castrocaroTerme:Location = { Location("Castrocaro Terme") }
    def castrovillari:Location = { Location("Castrovillari") }
    def catania:Location = { Location("Catania") }
    def catanzaro:Location = { Location("Catanzaro") }
    def catanzaroLido:Location = { Location("Catanzaro Lido") }
    def catanzaroLungomare:Location = { Location("Catanzaro-Lungomare") }
    def cattolica:Location = { Location("Cattolica") }
    def cavaDeTirreni:Location = { Location("Cava de'Tirreni") }
    def cavalese:Location = { Location("Cavalese") }
    def caveDelPredil:Location = { Location("Cave del Predil") }
    def caveDiCarrara:Location = { Location("Cave di Carrara") }
    def cecina:Location = { Location("Cecina") }
    def cefalu:Location = { Location("Cefalu") }
    def celano:Location = { Location("Celano") }
    def celleLigure:Location = { Location("Celle Ligure") }
    def cellole:Location = { Location("Cellole") }
    def cenateSotto:Location = { Location("Cenate Sotto") }
    def cento:Location = { Location("Cento") }
    def cepagatti:Location = { Location("Cepagatti") }
    def ceresolereale:Location = { Location("Ceresole Reale", Some(2247)) }
    def certosaDiPavia:Location = { Location("Certosa di Pavia") }
    def cervere:Location = { Location("Cervere") }
    def cervia:Location = { Location("Cervia") }
    def cervinia:Location = { Location("Cervinia", Some(2001)) }
    def cesanaTorinese:Location = { Location("Cesana Torinese") }
    def cesanoMaderno:Location = { Location("Cesano Maderno") }
    def cesena:Location = { Location("Cesena") }
    def cesenatico:Location = { Location("Cesenatico") }
    def cevo:Location = { Location("Cevo", Some(1054)) }
    def cherasco:Location = { Location("Cherasco") }
    def chiantiClassicoStage:Location = { Location("Chianti Classico Stage") }
    def chianale:Location = { Location("Chianale") }
    def chianciano:Location = { Location("Chianciano") }
    def chiancianoTerme:Location = { Location("Chianciano Terme") }
    def chiavari:Location = { Location("Chiavari") }
    def chiavenna:Location = { Location("Chiavenna") }
    def chieri:Location = { Location("Chieri") }
    def chiesaInValmalenco:Location = { Location("Chiesa in Valmalenco") }
    def chieti:Location = { Location("Chieti") }
    def chioggia:Location = { Location("Chioggia") }
    def cimaGrappa:Location = { Location("Cima Grappa") }
    def circuitoDelMugello:Location = { Location("Circuito del Mugello") }
    def circuitoDiLidoDAlbaro:Location = { Location("Circuito di Lido d'Albaro") }
    def cittaDiCastello:Location = { Location("Citta di Castello") }
    def cittaSantAngelo:Location = { Location("Citta Sant'Angelo") }
    def cittadella:Location = { Location("Cittadella") }
    def cittareale:Location = { Location("Cittareale") }
    def cividaleDelFruili:Location = { Location("Cividale del Friuli") }
    def civitanovaMarche:Location = { Location("Civitanova Marche") }
    def civitavecchia:Location = { Location("Civitavecchia") }
    def civitellaDiValDiChiana:Location = { Location("Civitella di Val di Chiana") }
    def cles:Location = { Location("Cles") }
    def clusone:Location = { Location("Clusone") }
    def colDuGalibierValloire:Location = { Location("Col du Galibier Valloire") }
    def collecchio:Location = { Location("Collecchio") }
    def colleDonBosco:Location = { Location("Colle Don Bosco") }
    def colliDiSanFermo:Location = { Location("Colli di San Fermo") }
    def collinaDiSuperga:Location = { Location("Collina di Superga") }
    def comacchio:Location = { Location("Comacchio") }
    def comerio:Location = { Location("Comerio") }
    def commezzadura:Location = { Location("Commezzadura") }
    def como:Location = { Location("Como") }
    def conegliano:Location = { Location("Conegliano") }
    def contursiTerme:Location = { Location("Contursi Terme") }
    def copertino:Location = { Location("Copertino") }
    def cordenons:Location = { Location("Cordenons") }
    def corinaldo:Location = { Location("Corinaldo") }
    def cornoAlleScale:Location = { Location("Corno alle Scale") }
    def cortinaDAmpezzo:Location = { Location("Cortina d'Ampezzo", Some(1224)) }
    def cortona:Location = { Location("Cortona") }
    def corvara:Location = { Location("Corvara") }
    def cosenza:Location = { Location("Cosenza") }
    def costalissoio:Location = { Location("Costalissoio", Some(1300)) }
    def courmayeur:Location = { Location("Courmayeur") }
    def courmayeurSkywayMonteBianco:Location = { Location("Courmayeur (Skyway Monte Bianco)") }
    def cremona:Location = { Location("Cremona") }
    def crotone:Location = { Location("Crotone") }
    def cuneo:Location = { Location("Cuneo") }

    def dalmine:Location = { Location("Dalmine") }
    def darfoBoarioTerme:Location = { Location("Darfo Boario Terme") }
    def desenzanoDelGarda:Location = { Location("Desenzano del Garda") }
    def diamante:Location = { Location("Diamante") }
    def dianoMarina:Location = { Location("Diano Marina") }
    def dimaro:Location = { Location("Dimaro") }
    def dobbiaco:Location = { Location("Dobbiaco") }
    def domodossola:Location = { Location("Domodossola") }
    def donoratico:Location = { Location("Donoratico") }
    def dozza:Location = { Location("Dozza") }

    def edolo:Location = { Location("Edolo") }
    def empoli:Location = { Location("Empoli") }
    def erba:Location = { Location("Erba") }
    def erbusco:Location = { Location("Erbusco") }
    def ercolano:Location = { Location("Ercolano") }
    def ertoECasso:Location = { Location("Erto e Casso") }
    def esanatoglia:Location = { Location("Esanatoglia") }
    def etna:Location = { Location("Etna") }

    def fabriano:Location = { Location("Fabriano") }
    def faenza:Location = { Location("Faenza") }
    def falcade:Location = { Location("Falcade") }
    def fano:Location = { Location("Fano") }
    def felino:Location = { Location("Felino") }
    def feltre:Location = { Location("Feltre") }
    def fermo:Location = { Location("Fermo") }
    def ferrara:Location = { Location("Ferrara") }
    def fidenza:Location = { Location("Fidenza") }
    def fieraDiPrimiero:Location = { Location("Fiera di Primiero") }
    def filottrano:Location = { Location("Filottrano") }
    def fioranoModenese:Location = { Location("Fiorano Modenese") }
    def firenze:Location = { Location("Firenze") }
    def fiuggi:Location = { Location("Fiuggi") }
    def florence:Location = { Location("Florence") }
    def foggia:Location = { Location("Foggia") }
    def folgaria:Location = { Location("Folgaria") }
    def folgarida:Location = { Location("Folgarida") }
    def foligno:Location = { Location("Foligno") }
    def follonica:Location = { Location("Follonica") }
    def fondoSarnonico:Location = { Location("Fondo/Sarnonico") }
    def foppolo:Location = { Location("Foppolo") }
    def forio:Location = { Location("Forio") }
    def forli:Location = { Location("Forlì") }
    def formia:Location = { Location("Formia") }
    def forteDeliaCreta:Location = { Location("Forte Delia Creta", Some(1254)) }
    def forteDeiMarmi:Location = { Location("Forte dei Marmi") }
    def fossacesia:Location = { Location("Fossacesia") }
    def fossano:Location = { Location("Fossano") }
    def frabosaSoprana:Location = { Location("Frabosa Soprana") }
    def francavillaAlMare:Location = { Location("Francavilla al Mare") }
    def frascati:Location = { Location("Frascati") }
    def frosinone:Location = { Location("Frosinone") }
    def fucecchio:Location = { Location("Fucecchio") }

    def gabicceMare:Location = { Location("Gabicce Mare") }
    def gaeta:Location = { Location("Gaeta") }
    def gallarate:Location = { Location("Gallarate") }
    def garda:Location = { Location("Garda") }
    def gardecciaValDiFassa:Location = { Location("Gardeccia-Val di Fassa") }
    def gardoneRiviera:Location = { Location("Gardone Riviera") }
    def gatteoAMare:Location = { Location("Gatteo a Mare") }
    def gemonaDelFriuli:Location = { Location("Gemona del Friuli") }
    def genoa:Location = { Location("Genoa") }
    def giffoniVallePiana:Location = { Location("Giffoni Valle Piana") }
    def giovinazzo:Location = { Location("Giovinazzo") }
    def giulianova:Location = { Location("Giulianova") }
    def gorizia:Location = { Location("Gorizia") }
    def gradiscaDIsonzo:Location = { Location("Gradisca d'Isonzo") }
    def grado:Location = { Location("Grado") }
    def granSassoDItalia:Location = { Location("Gran Sasso d'Italia") }
    def gravellonaToce:Location = { Location("Gravellona Toce") }
    def gressoneySaintJean:Location = { Location("Gressoney-Saint-Jean") }
    def grinzaneCavour:Location = { Location("Grinzane Cavour") }
    def grosseto:Location = { Location("Grosseto") }
    def gualdoTadino:Location = { Location("Gualdo Tadino") }
    def guardiagrele:Location = { Location("Guardiagrele") }
    def gubbio:Location = { Location("Gubbio") }
    def guilianova:Location = { Location("Guilianova") }

    def igeaMarina:Location = { Location("Igea Marina") }
    def ilCiocco:Location = { Location("Il Ciocco") }
    def imola:Location = { Location("Imola") }
    def imolaAutodromoEnzoEDinoFerrari:Location = { Location("Imola (Autodromo Enzo e Dino Ferrari)") }
    def imperia:Location = { Location("Imperia") }
    def indicatore:Location = { Location("Indicatore") }
    def inverigo:Location = { Location("Inverigo") }
    def ischia:Location = { Location("Ischia") }
    def iseo:Location = { Location("Iseo") }
    def isernia:Location = { Location("Isernia") }
    def ivrea:Location = { Location("Ivrea") }

    def jesi:Location = { Location("Jesi") }
    def jesolo:Location = { Location("Jesolo") }

    def lAquila:Location = { Location("L'Aquila") }
    def laMaddalena:Location = { Location("La Maddalena") }
    def laSpezia:Location = { Location("La Spezia") }
    def laThuile:Location = { Location("La Thuile") }
    def lagaLaceno:Location = { Location("Laga Laceno") }
    def lagoDiPiediluco:Location = { Location("Lago di Piediluco") }
    def lagoDiScanno:Location = { Location("Lago di Scanno") }
    def lagoLaceno:Location = { Location("Lago Laceno") }
    def lagoMiseno:Location = { Location("Lago Miseno") }
    def lainate:Location = { Location("Lainate") }
    def lamporecchio:Location = { Location("Lamporecchio") }
    def lanciano:Location = { Location("Lanciano") }
    def langhirano:Location = { Location("Langhirano") }
    def larciano:Location = { Location("Larciano") }
    def latina:Location = { Location("Latina") }
    def lauria:Location = { Location("Lauria") }
    def lavagna:Location = { Location("Lavagna") }
    def lavarone:Location = { Location("Lavarone") }
    def lecce:Location = { Location("Lecce") }
    def lecco:Location = { Location("Lecco") }
    def leccoPianDeiResinelli:Location = { Location("Lecco-Pian dei Resinelli") }
    def legnago:Location = { Location("Legnago") }
    def lerici:Location = { Location("Lerici") }
    def levicoTerme:Location = { Location("Levico Terme") }
    def lidoDAlbaro:Location = { Location("Lido d'Albaro") }
    def lidoDegliEstensi:Location = { Location("Lido degli Estensi") }
    def lidoDelleNazioni:Location = { Location("Lido delle Nazioni") }
    def lidoDiCaldonazzo:Location = { Location("Lido di Caldonazzo") }
    def lidoDiCamaiore:Location = { Location("Lido di Camaiore") }
    def lidoDiJesolo:Location = { Location("Lido di Jesolo") }
    def lignanoSabbiadoro:Location = { Location("Lignano Sabbiadoro") }
    def limonePiemonte:Location = { Location("Limone Piemonte") }
    def limoneSulGarda:Location = { Location("Limone sul Garda") }
    def lissone:Location = { Location("Lissone") }
    def livigno:Location = { Location("Livigno", Some(1816)) }
    def livorno:Location = { Location("Livorno") }
    def loano:Location = { Location("Loano") }
    def lodi:Location = { Location("Lodi") }
    def lodrino:Location = { Location("Lodrino", Some(736)) }
    def longarne:Location = { Location("Longarne") }
    def longarone:Location = { Location("Longarone") }
    def loreto:Location = { Location("Loreto") }
    def loretoAprutino:Location = { Location("Loreto Aprutino") }
    def lovere:Location = { Location("Lovere") }
    def lucca:Location = { Location("Lucca") }
    def lucera:Location = { Location("Lucera") }
    def lugo:Location = { Location("Lugo") }
    def luino:Location = { Location("Luino") }
    def lumezzane:Location = { Location("Lumezzane") }

    def macerata:Location = { Location("Macerata") }
    def macugnaga:Location = { Location("Macugnaga") }
    def maddaloni:Location = { Location("Maddaloni") }
    def madesimo:Location = { Location("Madesimo") }
    def madonnaDiCampiglio:Location = { Location("Madonna di Campiglio", Some(1715)) }
    def madonnaDiSanLuca:Location = { Location("Madonna di San Luca") }
    def maielletta:Location = { Location("Maielletta") }
    def malcesine:Location = { Location("Malcesine") }
    def male:Location = { Location("Male") }
    def maniago:Location = { Location("Maniago") }
    def mantua:Location = { Location("Mantua") }
    def maratea:Location = { Location("Maratea") }
    def marcianise:Location = { Location("Marcianise") }
    def marconiaDiPisticci:Location = { Location("Marconia di Pisticci") }
    def mareo:Location = { Location("Mareo") }
    def margheritaDiSavoia:Location = { Location("Margherita di Savoia") }
    def marinaDiAscea:Location = { Location("Marina di Ascea") }
    def marinaDiCarrara:Location = { Location("Marina di Carrara") }
    def marinaDiGrosseto:Location = { Location("Marina di Grosseto") }
    def marinaDiMassa:Location = { Location("Marina di Massa") }
    def marinaDiPietrasanta:Location = { Location("Marina di Pietrasanta") }
    def marinaDiPisa:Location = { Location("Marina di Pisa") }
    def marinaDiRavenna:Location = { Location("Marina di Ravenna") }
    def marinaDiSanVito:Location = { Location("Marina di San Vito") }
    def marinaRomea:Location = { Location("Marina Romea") }
    def marinoDiMassa:Location = { Location("Marino di Massa") }
    def marmolada:Location = { Location("Marmolada") }
    def marostica:Location = { Location("Marostica") }
    def marotta:Location = { Location("Marotta") }
    def marsala:Location = { Location("Marsala") }
    def martell:Location = { Location("Martell") }
    def massiccioDelSirino:Location = { Location("Massiccio del Sirino") }
    def matera:Location = { Location("Matera") }
    def mazzin:Location = { Location("Mazzin") }
    def meda:Location = { Location("Meda") }
    def melfi:Location = { Location("Melfi") }
    def mentana:Location = { Location("Mentana") }
    def merano:Location = { Location("Merano") }
    def merano2000:Location = { Location("Merano 2000") }
    def mercogliano:Location = { Location("Mercogliano") }
    def mergozzo:Location = { Location("Mergozzo") }
    def messina:Location = { Location("Messina") }
    def mestre:Location = { Location("Mestre") }
    def metaponto:Location = { Location("Metaponto") }
    def mezzocorona:Location = { Location("Mezzocorona") }
    def mezzolombardo:Location = { Location("Mezzolombardo") }
    def milano:Location = { Location("Milano") }
    def milazzo:Location = { Location("Milazzo") }
    def mira:Location = { Location("Mira") }
    def mirandola:Location = { Location("Mirandola") }
    def misurina:Location = { Location("Misurina") }
    def modena:Location = { Location("Modena") }
    def modica:Location = { Location("Modica") }
    def modigiliana:Location = { Location("Modigiliana") }
    def moena:Location = { Location("Moena") }
    def molaDiBari:Location = { Location("Mola di Bari") }
    def molfetta:Location = { Location("Molfetta") }
    def molveno:Location = { Location("Molveno") }
    def mondolfo:Location = { Location("Mondolfo") }
    def mondovi:Location = { Location("Mondovi") }
    def mondragone:Location = { Location("Mondragone") }
    def monesi:Location = { Location("Monesi") }
    def montalcino:Location = { Location("Montalcino") }
    def montaltoDiCastro:Location = { Location("Montalto di Castro") }
    def monteArgentario:Location = { Location("Monte Argentario") }
    def monteDiProcida:Location = { Location("Monte di Procida") }
    def monteSanVicino:Location = { Location("Monte San Vicino") }
    def montebelluna:Location = { Location("Montebelluna") }
    def montecampione:Location = { Location("Montecampione", Some(1200)) }
    def montecassino:Location = { Location("Montecassino") }
    def montecatini:Location = { Location("Montecatini") }
    def montecatiniTerme:Location = { Location("Montecatini Terme") }
    def montecchioMaggiore:Location = { Location("Montecchio Maggiore") }
    def montecopiolo:Location = { Location("Montecopiolo") }
    def montefalco:Location = { Location("Montefalco") }
    def montefiascone:Location = { Location("Montefiascone") }
    def montelibretti:Location = { Location("Montelibretti") }
    def montevarchi:Location = { Location("Montevarchi") }
    def montella:Location = { Location("Montella") }
    def montello:Location = { Location("Montello", Some(242)) }
    def montelucoDiSpoleto:Location = { Location("Monteluco di Spoleto") }
    def monteneroDiBisaccia:Location = { Location("Montenero di Bisaccia") }
    def montepulciano:Location = { Location("Montepulciano") }
    def monterotondoMarittimo:Location = Location("Monterotondo Marittimo")
    def montesanoSullaMarcellana:Location = { Location("Montesano sulla Marcellana") }
    def montesilvano:Location = { Location("Montesilvano") }
    def monticelloBrianza:Location = { Location("Monticello Brianza") }
    def monza:Location = { Location("Monza") }
    def morbegno:Location = { Location("Morbegno") }
    def mori:Location = { Location("Mori") }
    def muggio:Location = { Location("Muggio") }
    def museoDelGhisallo:Location = { Location("Museo del Ghisallo") }

    def naples:Location = { Location("Naples") }
    def narniScalo:Location = { Location("Narni Scalo") }
    def nervesaDellaBattaglia:Location = { Location("Nervesa della Battaglia") }
    def nettuno:Location = { Location("Nettuno") }
    def neumarkt:Location = { Location("Neumarkt") }
    def nevegal:Location = { Location("Nevegal") }
    def nicotera:Location = { Location("Nicotera") }
    def noale:Location = { Location("Noale") }
    def nola:Location = { Location("Nola") }
    def noto:Location = { Location("Noto") }
    def novara:Location = { Location("Novara") }
    def noviLigure:Location = { Location("Novi Ligure") }
    def numana:Location = { Location("Numana") }

    def olbia:Location = { Location("Olbia") }
    def oneglia:Location = { Location("Oneglia") }
    def orbetello:Location = { Location("Orbetello") }
    def oropa:Location = { Location("Oropa") }
    def ortaSanGiulio:Location = { Location("Orta San Giulio") }
    def ortisei:Location = { Location("Ortisei") }
    def ortiseiStUlrichValGardena:Location = { Location("Ortisei/St. Ulrich (Val Gardena)") }
    def ortona:Location = { Location("Ortona") }
    def orvieto:Location = { Location("Orvieto") }
    def osimo:Location = { Location("Osimo", Some(265)) }
    def ostuni:Location = { Location("Ostuni") }
    def ozegna:Location = { Location("Ozegna") }

    def padua:Location = { Location("Padua") }
    def padula:Location = { Location("Padula") }
    def paestum:Location = { Location("Paestum") }
    def palazzoloSullOglio:Location = { Location("Palazzolo sull'Oglio") }
    def palermo:Location = { Location("Palermo") }
    def palinuro:Location = { Location("Palinuro") }
    def palmanova:Location = { Location("Palmanova") }
    def palmi:Location = { Location("Palmi") }
    def panicaglioraMarliana:Location = { Location("Panicagliora (Marliana)") }
    def paola:Location = { Location("Paola") }
    def parabiago:Location = { Location("Parabiago") }
    def parma:Location = { Location("Parma") }
    def passoCornello:Location = { Location("Passo Cornello", Some(814)) }
    def passoDelBocco:Location = { Location("Passo del Bocco") }
    def passoDelTonale:Location = { Location("Passo del Tonale") }
    def passoDiPampeagno:Location = { Location("Passo di Pampeagno") }
    def passoDiSanPellegrino:Location = { Location("Passo di San Pellegrino") }
    def pavia:Location = { Location("Pavia") }
    def pedara:Location = { Location("Pedara") }
    def pedavena:Location = { Location("Pedavena") }
    def peio:Location = { Location("Peio") }
    def peioTerme:Location = { Location("Peio Terme") }
    def penne:Location = { Location("Penne") }
    def pergola:Location = { Location("Pergola") }
    def perugia:Location = { Location("Perugia") }
    def pesaro:Location = { Location("Pesaro") }
    def pescara:Location = { Location("Pescara") }
    def pescasseroli:Location = { Location("Pescasseroli") }
    def peschici:Location = { Location("Peschici") }
    def pescoSannita:Location = { Location("Pesco Sannita") }
    def pescocostanzo:Location = { Location("Pescocostanzo") }
    def pfalzen:Location = { Location("Pfalzen") }
    def piacenza:Location = { Location("Piacenza") }
    def pianDelRe:Location = { Location("Pian del Re") }
    def pianDelResinelli:Location = { Location("Pian del Resinelli") }
    def piancavallo:Location = { Location("Piancavallo") }
    def piancogno:Location = { Location("Piancogno") }
    def pienza:Location = { Location("Pienza") }
    def pietraLigure:Location = { Location("Pietra Ligure") }
    def pietrasanta:Location = { Location("Pietrasanta") }
    def pieveDiCadore:Location = { Location("Pieve di Cadore") }
    def pieveDiCento:Location = { Location("Pieve di Cento") }
    def pila:Location = { Location("Pila") }
    def pinerolo:Location = { Location("Pinerolo") }
    def pinetaDiCervia:Location = { Location("Pineta di Cervia") }
    def pinzolo:Location = { Location("Pinzolo") }
    def piombino:Location = { Location("Piombino") }
    def pisa:Location = { Location("Pisa") }
    def pistoia:Location = { Location("Pistoia") }
    def pizzo:Location = { Location("Pizzo") }
    def pizzoCalabro:Location = { Location("Pizzo Calabro") }
    def planDeCorones:Location = { Location("Plan de Corones", Some(2273)) }
    def planDiMontecampione:Location = { Location("Plan di Montecampione", Some(1732)) }
    def poggibonsi:Location = { Location("Poggibonsi") }
    def poggio:Location = { Location("Poggio") }
    def poggioDiSanRemo:Location = { Location("Poggio di San Remo") }
    def policastroBussentino:Location = { Location("Policastro Bussentino") }
    def policoro:Location = { Location("Policoro") }
    def polla:Location = { Location("Polla") }
    def polsa:Location = { Location("Polsa") }
    def pomarance:Location = { Location("Pomarance") }
    def pompeii:Location = { Location("Pompeii") }
    def pontSaintMartin:Location = { Location("Pont-Saint-Martin") }
    def ponte:Location = { Location("Ponte") }
    def ponteDiLegno:Location = { Location("Ponte di Legno") }
    def pontechianale:Location = { Location("Pontechianale") }
    def pontedera:Location = { Location("Pontedera") }
    def pontoglio:Location = { Location("Pontoglio") }
    def pontremoli:Location = { Location("Pontremoli") }
    def pordenone:Location = { Location("Pordenone") }
    def porrettaTerme:Location = { Location("Porretta Terme") }
    def porteferraio:Location = { Location("Porteferraio") }
    def portoAzzurro:Location = { Location("Porto Azzurro") }
    def portoRecanati:Location = { Location("Porto Recanati") }
    def portoSanGiorgio:Location = { Location("Porto San Giorgio") }
    def portoSantElpidio:Location = { Location("Porto Sant'Elpidio") }
    def portocivitanova:Location = { Location("Portocivitanova") }
    def portoferraio:Location = { Location("Portoferraio") }
    def portorose:Location = { Location("Portorose") }
    def portovenere:Location = { Location("Portovenere") }
    def potenza:Location = { Location("Potenza") }
    def pozzaDiFassa:Location = { Location("Pozza di Fassa") }
    def praiaAMare:Location = { Location("Praia a Mare") }
    def pratiDiTivo:Location = { Location("Prati di Tivo") }
    def prato:Location = { Location("Prato") }
    def pratoNevoso:Location = { Location("Prato Nevoso", Some(1607)) }
    def predappio:Location = { Location("Predappio") }
    def predazzo:Location = { Location("Predazzo") }
    def presolana:Location = { Location("Presolana") }

    def quartoDeiMille:Location = { Location("Quarto dei Mille") }

    def racconigi:Location = { Location("Racconigi") }
    def rapallo:Location = { Location("Rapallo") }
    def ravello:Location = { Location("Ravello") }
    def ravenna:Location = { Location("Ravenna") }
    def recanati:Location = { Location("Recanati") }
    def recoaroTerme:Location = { Location("Recoaro Terme") }
    def reggello:Location = { Location("Reggello") }
    def reggioCalabria:Location = { Location("Reggio Calabria") }
    def reggioEmilia:Location = { Location("Reggio Emilia") }
    def riccione:Location = { Location("Riccione") }
    def riesePioX:Location = { Location("Riese Pio X") }
    def rieti:Location = { Location("Rieti") }
    def rifugioPanarotta:Location = { Location("Rifugio Panarotta") }
    def rimini:Location = { Location("Rimini") }
    def rioMarina:Location = { Location("Rio Marina") }
    def rioloTerme:Location = { Location("Riolo Terme") }
    def riomaggiore:Location = { Location("Riomaggiore") }
    def rivaDelGarda:Location = { Location("Riva del Garda") }
    def rivaroloCanavese:Location = { Location("Rivarolo Canavese") }
    def rivisondoli:Location = { Location("Rivisondoli") }
    def roccaDiCambio:Location = { Location("Rocca di Cambio") }
    def roccaDiPapa:Location = { Location("Rocca di Papa") }
    def roccaPietore:Location = { Location("Rocca Pietore") }
    def roccaraso:Location = { Location("Roccaraso", Some(1252)) }
    def roccarasoAremogna:Location = { Location("Roccaraso (Aremogna)") }
    def rodiGarganico:Location = { Location("Rodi Garganico") }
    def rome:Location = { Location("Rome") }
    def rossantoVeneto:Location = { Location("Rossanto Veneto") }
    def rovato:Location = { Location("Rovato") }
    def rovereto:Location = { Location("Rovereto") }
    def rovetta:Location = { Location("Rovetta") }
    def rovigo:Location = { Location("Rovigo") }

    def sacroMonteDiVarese:Location = { Location("Sacro Monte di Varese") }
    def saintVincent:Location = { Location("Saint-Vincent") }
    def salaBaganza:Location = { Location("Sala Baganza") }
    def salaConsilina:Location = { Location("Sala Consilina") }
    def salerno:Location = { Location("Salerno") }
    def saliceTerme:Location = { Location("Salice Terme") }
    def salo:Location = { Location("Salo") }
    def salsomaggioreTerme:Location = { Location("Salsomaggiore Terme") }
    def saltara:Location = { Location("Saltara") }
    def saluzzo:Location = { Location("Saluzzo") }
    def sampeyre:Location = { Location("Sampeyre") }
    def sanBenedettoDelTronto:Location = { Location("San Benedetto del Tronto") }
    def sanCandido:Location = { Location("San Candido") }
    def sanDonaDiPiave:Location = { Location("San Dona di Piave") }
    def sanGiacomoDiRoburent:Location = { Location("San Giacomo di Roburent") }
    def sanGiacomoDiValleCastellana:Location = { Location("San Giacomo di Valle Castellana") }
    def sanGiorgioDelSannio:Location = { Location("San Giorgio del Sannio") }
    def sanGiorgioPiacentino:Location = { Location("San Giorgio Piacentino") }
    def sanGiovanniRotondo:Location = { Location("San Giovanni Rotondo") }
    def sanLorenzoAlMare:Location = { Location("San Lorenzo al Mare") }
    def sanLuca:Location = { Location("San Luca") }
    def sanMarcelloPistoiese:Location = { Location("San Marcello Pistoiese") }
    def sanMartinoDiCastrozza:Location = { Location("San Martino di Castrozza", Some(1487)) }
    def sanPellegrinoTerme:Location = { Location("San Pellegrino Terme") }
    def sanRemo:Location = { Location("San Remo") }
    def sanRomolo:Location = { Location("San Romolo") }
    def sanSalvo:Location = { Location("San Salvo") }
    def sanSevero:Location = { Location("San Severo") }
    def sanVendemiano:Location = { Location("San Vendemiano") }
    def sanVigilloDiMarebbe:Location = { Location("San Vigillo di Marebbe") }
    def sanVincenzo:Location = { Location("San Vincenzo") }
    def sanVitoAlTagliamento:Location = { Location("San Vito al Tagliamento") }
    def sanVitoDiCadore:Location = { Location("San Vito di Cadore") }
    def sanctuarioDiVicoforte:Location = { Location("Sanctuario di Vicoforte") }
    def sansepolcro:Location = { Location("Sansepolcro") }
    def santAnnaDiVinadio:Location = { Location("Sant'Anna di Vinadio") }
    def santaCaterinaDiValfurva:Location = { Location("Santa Caterina di Valfurva") }
    def santaMariaCapuaVetere:Location = { Location("Santa Maria Capua Vetere") }
    def santaMargheritaLigure:Location = { Location("Santa Margherita Ligure") }
    def santaMariaDelCedro:Location = { Location("Santa Maria del Cedro") }
    def santaMariaDellaVersa:Location = { Location("Santa Maria della Versa") }
    def santaMariaDiSala:Location = { Location("Santa Maria di Sala") }
    def santaNinfa:Location = { Location("Santa Ninfa") }
    def santarcangeloDiRomagna:Location = { Location("Santarcangelo di Romagna") }
    def santuarioDiOropa:Location = { Location("Santuario di Oropa") }
    def santuarioNostraSignoraDellaGuardia:Location = { Location("Santuario Nostra Signora della Guardia") }
    def sanuarioDiVicoforte:Location = { Location("Sanuario di Vicoforte") }
    def sappada:Location = { Location("Sappada") }
    def sapri:Location = { Location("Sapri") }
    def sarezzo:Location = { Location("Sarezzo") }
    def sarnanoSassotetto:Location = Location("Sarnano Sassotetto")
    def sarnico:Location = { Location("Sarnico") }
    def sarnonico:Location = { Location("Sarnonico") }
    def saronno:Location = { Location("Saronno") }
    def sarzana:Location = { Location("Sarzana") }
    def sassari:Location = { Location("Sassari") }
    def sassono:Location = { Location("Sassono") }
    def sassuolo:Location = { Location("Sassuolo") }
    def sauzeDOulx:Location = { Location("Sauze d'Oulx") }
    def savigliano:Location = { Location("Savigliano") }
    def savona:Location = { Location("Savona") }
    def scalea:Location = { Location("Scalea") }
    def scalenghe:Location = { Location("Scalenghe") }
    def scanno:Location = { Location("Scanno") }
    def scarperia:Location = { Location("Scarperia") }
    def schio:Location = { Location("Schio") }
    def schlanders:Location = { Location("Schlanders") }
    def schnals:Location = { Location("Schnals") }
    def sciacca:Location = { Location("Sciacca") }
    def scilla:Location = { Location("Scilla") }
    def sellaValsugana:Location = { Location("Sella Valsugana") }
    def selva:Location = { Location("Selva") }
    def selvaDiFasano:Location = { Location("Selva di Fasano") }
    def selvaDiValGardena:Location = { Location("Selva di Val Gardena") }
    def selvino:Location = { Location("Selvino") }
    def senigallia:Location = { Location("Senigallia") }
    def seravezza:Location = { Location("Seravezza") }
    def seregno:Location = { Location("Seregno") }
    def sernigaDiSalo:Location = { Location("Serniga di Salo") }
    def serraSanBruno:Location = { Location("Serra San Bruno") }
    def serravilleScrivia:Location = { Location("Serraville Scrivia") }
    def sestola:Location = { Location("Sestola") }
    def sestriere:Location = { Location("Sestrière", Some(2035)) }
    def sestriLevante:Location = { Location("Sestri Levante") }
    def siena:Location = { Location("Siena") }
    def sillian:Location = { Location("Sillian") }
    def silviMarina:Location = { Location("Silvi Marina") }
    def sinalunga:Location = { Location("Sinalunga") }
    def siracusa:Location = { Location("Siracusa") }
    def sirmione:Location = { Location("Sirmione") }
    def soave:Location = { Location("Soave") }
    def sondrio:Location = { Location("Sondrio") }
    def sora:Location = { Location("Sora") }
    def sorrento:Location = { Location("Sorrento") }
    def sottomarinaDiChioggia:Location = { Location("Sottomarina di Chioggia") }
    def spilimbergo:Location = { Location("Spilimbergo") }
    def spoleto:Location = { Location("Spoleto") }
    def spondigna:Location = { Location("Spondigna") }
    def stradella:Location = { Location("Stradella") }
    def sulden:Location = { Location("Sulden") }
    def sulmona:Location = { Location("Sulmona") }
    def susa:Location = { Location("Susa") }

    def tabianoTerme:Location = { Location("Tabiano Terme") }
    def taormina:Location = { Location("Taormina") }
    def taranto:Location = { Location("Taranto") }
    def tarvisio:Location = { Location("Tarvisio") }
    def teano:Location = { Location("Teano") }
    def teleseTerme:Location = { Location("Telese Terme") }
    def tempioPausania:Location = { Location("Tempio Pausania") }
    def teramo:Location = { Location("Teramo") }
    def termLuigiane:Location = { Location("Term Luigiane") }
    def termamo:Location = { Location("Termamo") }
    def termeDiComano:Location = { Location("Terme di Comano") }
    def termeEuganee:Location = { Location("Terme Euganee") }
    def termeLaCalda:Location = { Location("Terme La Calda") }
    def termeLuigiane:Location = { Location("Terme Luigiane") }
    def termoli:Location = { Location("Termoli") }
    def terni:Location = { Location("Terni") }
    def terracina:Location = { Location("Terracina") }
    def tirano:Location = { Location("Tirano") }
    def tivoli:Location = { Location("Tivoli") }
    def todi:Location = { Location("Todi") }
    def tolmezzo:Location = { Location("Tolmezzo") }
    def torino:Location = { Location("Torino") }
    def tortoli:Location = { Location("Tortolì") }
    def tortona:Location = { Location("Tortona") }
    def tortoreto:Location = { Location("Tortoreto") }
    def tortoretoLido:Location = { Location("Tortoreto Lido") }
    def tramin:Location = { Location("Tramin") }
    def trani:Location = { Location("Trani") }
    def trento:Location = { Location("Trento") }
    def trescore:Location = { Location("Trescore Balneario") }
    def trescoreBalneario:Location = { Location("Trescore Balneario") }
    def trevi:Location = Location("Trevi")
    def treviglio:Location = { Location("Treviglio") }
    def treviso:Location = { Location("Treviso") }
    def trieste:Location = { Location("Trieste") }
    def tropea:Location = { Location("Tropea") }
    def turbigo:Location = { Location("Turbigo") }
    def turin:Location = { Location("Turin") }

    def udine:Location = { Location("Udine") }
    def ulivetoTerme:Location = { Location("Uliveto Terme") }
    def urbania:Location = { Location("Urbania") }
    def urbino:Location = { Location("Urbino") }
    def urtijei:Location = { Location("Urtijei") }

    def vajoletTowers:Location = { Location("Vajolet Towers") }
    def valMartello:Location = { Location("Val Martello") }
    def valdaora:Location = { Location("Valdaora") }
    def valdengo:Location = { Location("Valdengo") }
    def valdobbiadene:Location = { Location("Valdobbiadene") }
    def valenza:Location = { Location("Valenza") }
    def valicoDelVetriolo:Location = { Location("Valico del Vetriolo") }
    def valicoDiPietraRossa:Location = { Location("Valico di Pietra Rossa", Some(674)) }
    def vallombrosa:Location = { Location("Vallombrosa") }
    def valmontone:Location = { Location("Valmontone") }
    def valnonteyDiCogne:Location = { Location("Valnontey di Cogne") }
    def varazze:Location = { Location("Varazze") }
    def varese:Location = { Location("Varese") }
    def varzi:Location = { Location("Varzi") }
    def vasto:Location = { Location("Vasto") }
    def vedelago:Location = { Location("Vedelago") }
    def veneriaReale:Location = { Location("Veneria Reale") }
    def venezia:Location = { Location("Venezia") }
    def venice:Location = { Location("Venice") }
    def veniceLido:Location = { Location("Lido (Venice)") }
    def verbania:Location = { Location("Verbania") }
    def vercelli:Location = { Location("Vercelli") }
    def verona:Location = { Location("Verona") }
    def verres:Location = { Location("Verres") }
    def vestone:Location = { Location("Vestone") }
    def viareggio:Location = { Location("Viareggio") }
    def viboValentia:Location = { Location("Vibo Valentia") }
    def vicenza:Location = { Location("Vicenza") }
    def vicenzaMonteBerico:Location = { Location("Vicenza (Monte Berico)") }
    def vieste:Location = { Location("Vieste") }
    def vigevano:Location = { Location("Vigevano") }
    def viggiano:Location = { Location("Viggiano") }
    def vigoDiFassa:Location = { Location("Vigo di Fassa") }
    def villaDiTirano:Location = { Location("Villa di Tirano") }
    def villaSanGiovanni:Location = { Location("Villa San Giovanni") }
    def villafranca:Location = { Location("Villafranca") }
    def villafrancaTirrena:Location = { Location("Villafranca Tirrena") }
    def villapianaLido:Location = { Location("Villapiana Lido") }
    def vinci:Location = { Location("Vinci") }
    def viterbo:Location = { Location("Viterbo") }
    def vittorioVeneto:Location = { Location("Vittorio Veneto") }
    def voghera:Location = { Location("Voghera") }

    def zingonia:Location = { Location("Zingonia") }

    // Italian mountains
    def monteTerminillo = Location("Monte Terminillo", Some(2217))
}

object DutchLocations {

    implicit val country:Country = Netherlands

    def arnhem:Location           = { Location("Arnhem") }
    def amsterdam:Location        = { Location("Amsterdam") }
    def apeldoorn:Location        = { Location("Apeldoorn") }
    def assen:Location            = { Location("Assen") }
    def bergEnTerblijt:Location   = { Location("Berg en Terblijt") }
    def breda:Location            = { Location("Breda") }
    def elsloo:Location           = { Location("Elsloo") }
    def emmen:Location            = { Location("Emmen") }
    def groningen:Location        = { Location("Groningen") }
    def heerlen:Location          = { Location("Heerlen") }
    def helmond:Location          = { Location("Helmond") }
    def leiden:Location           = { Location("Leiden") }
    def maastricht:Location       = { Location("Maastricht") }
    def meerssen:Location         = { Location("Meerssen") }
    def middleburg:Location       = { Location("Middleburg") }
    def nijmegen:Location         = { Location("Nijmegen") }
    def rotterdam:Location        = { Location("Rotterdam") }
    def scheveningen:Location     = { Location("Scheveningen") }
    def sHertogenbosch:Location   = { Location("'s-Hertogenbosch") }
    def sintWillebrord:Location   = { Location("Sint Willebrord") }
    def utrecht:Location          = { Location("Utrecht") }
    def valkenburg:Location       = { Location("Valkenburg") }
    def venlo:Location            = { Location("Venlo") }
    def zeeland:Location          = { Location("Zeeland") }
    def zutphen:Location          = { Location("Zutphen") }
}

object SwissLocations {

    implicit val country:Country = Switzerland

    def basel:Location          = { Location("Basel") } 
    def bern:Location           = { Location("Bern") } 
    def cransMontana:Location   = { Location("Crans-Montana", Some(1670)) }
    def fribourg:Location       = { Location("Fribourg") } 
    def geneva:Location         = { Location("Geneva") } 
    def laChauxDeFonds:Location = { Location("La Chaux-de-Fonds") } 
    def lausanne:Location       = { Location("Lausanne") } 
    def lenzerheide:Location    = { Location("Lenzerheide") } 
    def leukerbad:Location      = { Location("Leukerbad") } 
    def locarno:Location        = { Location("Locarno") } 
    def lugano:Location         = { Location("Lugano") } 
    def martigny:Location       = { Location("Martigny") } 
    def melide:Location         = { Location("Melide") } 
    def mendrisio:Location      = { Location("Mendrisio") } 
    def mohin:Location          = { Location("Mohin") } 
    def neuchatel:Location      = { Location("Neuchatel") } 
    def saasFee:Location        = { Location("Saas Fee") } 
    def saintMoritz:Location    = { Location("Saint Moritz", Some(1822)) } 
    def sion:Location           = { Location("Sion") } 
    def verbier:Location        = { Location("Verbier", Some(1468)) } 
    def zurich:Location         = { Location("Zurich") }

    // Swiss Mountains
    def monteGeneroso = { Location("Monte Generoso", Some(1158)) }
}

object BritishLocations {

    implicit val country:Country = UnitedKingdom

    def brighton:Location   = { Location("Brighton") }
    def cambridge:Location  = { Location("Cambridge") }
    def canterbury:Location = { Location("Canterbury") }
    def dover:Location      = { Location("Dover") }
    def harrogate:Location  = { Location("Harrogate") } 
    def leeds:Location      = { Location("Leeds") }
    def london:Location     = { Location("London") }
    def plymouth:Location   = { Location("Plymouth") }
    def portsmouth:Location = { Location("Portsmouth") }
    def sheffield:Location  = { Location("Sheffield") }
    def york:Location       = { Location("York") }
}

object WestGermanLocations {

    implicit val country:Country = WestGermany

    def cologne:Location    = { Location("Cologne") }
    def felsberg:Location   = { Location("Felsberg") }
    def frankfurt:Location  = { Location("Frankfurt") }
    def freiburg:Location   = { Location("Freiburg") }
    def karlsruhe:Location  = { Location("Karlsruhe") }
    def pforzheim:Location  = { Location("Pforzheim") }
    def saarlouis:Location  = { Location("Saarlouis") }
    def stuttgart:Location  = { Location("Stuttgart") }
    def westBerlin:Location = { Location("West Berlin") }
    def wiesbaden:Location  = { Location("Wiesbaden") }
}
