package parcoursdb

sealed trait Country
case object Andorra extends Country
case object Argentina extends Country
case object Austria extends Country
case object Australia extends Country
case object Belgium extends Country
case object Canada extends Country
case object Colombia extends Country
case object Croatia extends Country
case object Denmark extends Country
case object Estonia extends Country
case object Ethiopia extends Country
case object France extends Country
case object Germany extends Country
case object WestGermany extends Country
case object Greece extends Country
case object Ireland extends Country
case object Israel extends Country
case object Italy extends Country
case object Latvia extends Country
case object Luxembourg extends Country
case object Norway extends Country
case object Monaco extends Country
case object Netherlands extends Country
case object Poland extends Country
case object Portugal extends Country
case object PuertoRico extends Country
case object RepublicOfSouthAfrica extends Country
case object Russia extends Country
case object Spain extends Country
case object SanMarino extends Country
case object Slovenia extends Country
case object Slovakia extends Country
case object Sweden extends Country
case object Switzerland extends Country
case object UnitedKingdom extends Country
case object UnitedStates extends Country
